#!/usr/bin/env python3
"""Regenerates src/gobridge_embed.cpp: the Go sources of the bridge (tools/gobridge/) compiled
into the `nusa` binary, so `nusa go add` works wherever the binary is.

    tools/embed_gobridge.py > src/gobridge_embed.cpp
"""
import os

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gobridge")
files = {"bridge.go": "bridge.go", "gen/main.go": os.path.join("gen", "main.go")}
print("// GENERATED by tools/embed_gobridge.py from tools/gobridge/ -- do not edit by hand.")
print("#include \"gobridge.hpp\"")
print()
print("namespace gobridge {")
print()
print("const std::vector<EmbeddedFile>& embeddedFiles() {")
print("    static const std::vector<EmbeddedFile> files = {")
for name, rel in files.items():
    src = open(os.path.join(root, rel)).read()
    assert ')NSGO"' not in src
    # A raw string literal has a length limit on some compilers: split into chunks.
    chunks = [src[i:i + 8000] for i in range(0, len(src), 8000)]
    print(f'        {{"{name}",')
    for c in chunks:
        print('         R"NSGO(' + c + ')NSGO"')
    print("        },")
print("    };")
print("    return files;")
print("}")
print()
print("}  // namespace gobridge")
