#!/usr/bin/env python3
"""Regenerates src/stdlib_embed.cpp: the NSL sources in lib/ (the Python-style standard modules)
compiled into the `nusa` binary.

    tools/embed_lib.py > src/stdlib_embed.cpp

A module is lib/<name>.ns; `import a.b` looks for lib/a_b.ns.
"""
import os

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "lib")
print("// GENERATED by tools/embed_lib.py from lib/ -- do not edit by hand.")
print("#include <string>")
print("#include <unordered_map>")
print()
print("namespace pystd {")
print()
print("const char* embeddedLibModule(const std::string& name) {")
print("    static const std::unordered_map<std::string, const char*> mods = {")
for fn in sorted(os.listdir(root)):
    if not fn.endswith(".ns"):
        continue
    src = open(os.path.join(root, fn)).read()
    assert ')NSLIB"' not in src
    chunks = [src[i:i + 8000] for i in range(0, len(src), 8000)]
    print(f'        {{"{fn[:-3]}",')
    for c in chunks:
        print('         R"NSLIB(' + c + ')NSLIB"')
    print("        },")
print("    };")
print("    auto it = mods.find(name);")
print("    return it == mods.end() ? nullptr : it->second;")
print("}")
print()
print("}  // namespace pystd")
