#!/usr/bin/env python3
"""Regenerates src/tls_ca_bundle.cpp (the root certificates compiled into the binary as a
fallback when the machine has no CA bundle) from a PEM bundle.

    tools/gen_ca_bundle.py [/etc/ssl/certs/ca-certificates.crt] > src/tls_ca_bundle.cpp
"""
import re, sys

path = sys.argv[1] if len(sys.argv) > 1 else "/etc/ssl/certs/ca-certificates.crt"
pem = open(path).read()
certs = re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", pem, re.S)
print("// GENERATED by tools/gen_ca_bundle.py from %s -- do not edit by hand." % path)
print("// Root certificates (DER, base64) used only when no system CA bundle is found.")
print("#include <cstddef>")
print()
print("namespace tls {")
print("namespace x509 {")
print()
print("extern const char* const kEmbeddedRootCertsBase64[];")
print("extern const size_t kEmbeddedRootCertsCount;")
print()
print("const char* const kEmbeddedRootCertsBase64[] = {")
for c in certs:
    print('    "%s",' % "".join(c.split()))
print("};")
print("const size_t kEmbeddedRootCertsCount = %d;" % len(certs))
print()
print("}  // namespace x509")
print("}  // namespace tls")
