// GENERATED by tools/embed_gobridge.py from tools/gobridge/ -- do not edit by hand.
#include "gobridge.hpp"

namespace gobridge {

const std::vector<EmbeddedFile>& embeddedFiles() {
    static const std::vector<EmbeddedFile> files = {
        {"bridge.go",
         R"NSGO(// Nusantara <-> Go bridge (built as a c-shared plugin by `nusa go add`).
//
// One generic, reflection-based runtime serves every wrapped Go package: the generated
// registry_gen.go only lists what exists (functions, types, constants); this file knows how
// to call them. Values cross the plugin ABI as JSON text:
//
//   - numbers, strings, booleans, null, arrays and objects map to their Go counterparts;
//   - pointers, interfaces, funcs and channels stay on the Go side and are handed out as
//     handles: {"$h": "h12", "tipe": "*pkg.Type", "m": {"Method": <arity>, ...}};
//   - a Go func parameter is filled from {"$cb": "<queue>"}: Go calls are queued as events
//     that the Nusantara side drains (see the generated index.ns).
package main

/*
#include <stdlib.h>
#include <string.h>

typedef enum { NS_NULL = 0, NS_BOOL = 1, NS_NUMBER = 2, NS_STRING = 3 } NsType;
typedef struct { NsType type; int boolean; double number; char* str; int str_len; } NsValue;
typedef NsValue (*NsFn)(int argc, const NsValue* argv);
typedef void (*NsRegisterFn)(void* registry, const char* name, NsFn fn);

extern NsValue nsGoInvoke(int op, int argc, NsValue* argv);

static NsValue t_panggil(int argc, const NsValue* argv) { return nsGoInvoke(0, argc, (NsValue*)argv); }
static NsValue t_buat(int argc, const NsValue* argv) { return nsGoInvoke(1, argc, (NsValue*)argv); }
static NsValue t_field(int argc, const NsValue* argv) { return nsGoInvoke(2, argc, (NsValue*)argv); }
static NsValue t_setfield(int argc, const NsValue* argv) { return nsGoInvoke(3, argc, (NsValue*)argv); }
static NsValue t_konst(int argc, const NsValue* argv) { return nsGoInvoke(4, argc, (NsValue*)argv); }
static NsValue t_event(int argc, const NsValue* argv) { return nsGoInvoke(5, argc, (NsValue*)argv); }
static NsValue t_daftar(int argc, const NsValue* argv) { return nsGoInvoke(6, argc, (NsValue*)argv); }
static NsValue t_bebas(int argc, const NsValue* argv) { return nsGoInvoke(7, argc, (NsValue*)argv); }
static NsValue t_balas(int argc, const NsValue* argv) { return nsGoInvoke(8, argc, (NsValue*)argv); }

static void register_all(void* r, NsRegisterFn reg) {
    reg(r, "panggil", t_panggil);
    reg(r, "buat", t_buat);
    reg(r, "field", t_field);
    reg(r, "set_field", t_setfield);
    reg(r, "konst", t_konst);
    reg(r, "event", t_event);
    reg(r, "daftar", t_daftar);
    reg(r, "bebas", t_bebas);
    reg(r, "balas", t_balas);
}

static NsValue make_string(const char* s, int n) {
    NsValue v;
    memset(&v, 0, sizeof v);
    v.type = NS_STRING;
    v.str = (char*)malloc((size_t)n + 1);
    memcpy(v.str, s, (size_t)n);
    v.str[n] = 0;
    v.str_len = n;
    return v;
}
static NsValue make_null(void) { NsValue v; memset(&v, 0, sizeof v); return v; }
*/
import "C"

import (
	"context"
	"encoding"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net/http"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
	"unsafe"
)

//export ns_plugin_init
func ns_plugin_init(registry unsafe.Pointer, reg C.NsRegisterFn) { C.register_all(registry, reg) }

//export nusa_abi_version
func nusa_abi_version() C.int { return 2 }

func main() {}

// ---------------------------------------------------------------- handles ----

var (
	hmu     sync.Mutex
	handles = map[string]reflect.Value{}
	hnext   int
)

func newHandle(v reflect.Value) string {
	hmu.Lock()
	defer hmu.Unlock()
	hnext++
	id := "h" + strconv.Itoa(hnext)
	handles[id] = v
	return id
}

func lookupHandle(id string) (reflect.Value, bool) {
	hmu.Lock()
	defer hmu.Unlock()
	v, ok := handles[id]
	return v, ok
}

// Number of parameters the NSL wrapper takes. A variadic method reports 100+fixed: the
// wrapper takes the fixed arguments plus one list holding the variadic ones.
func methodArity(t reflect.Type, skip int) int {
	n := t.NumIn() - skip
	if t.IsVariadic() {
		return 100 + n - 1
	}
	return n
}

var methodCache sync.Map // reflect.Type -> map[string]int

func methodTable(t reflect.Type) map[string]int {
	if m, ok := methodCache.Load(t); ok {
		return m.(map[string]int)
	}
	out := map[string]int{}
	for i := 0; i < t.NumMethod(); i++ {
		m := t.Method(i)
		if t.Kind() == reflect.Interface {
			out[m.Name] = methodArity(m.Type, 0)
		} else {
			out[m.Name] = methodArity(m.Type, 1) // drop the receiver
		}
	}
	// A struct value's pointer-receiver methods are reachable through a pointer copy.
	if t.Kind() != reflect.Ptr && t.Kind() != reflect.Interface {
		pt := reflect.PtrTo(t)
		for i := 0; i < pt.NumMethod(); i++ {
			m := pt.Method(i)
			if _, dup := out[m.Name]; !dup {
				out[m.Name] = methodArity(m.Type, 1)
			}
		}
	}
	methodCache.Store(t, out)
	return out
}

func hasMethods(t reflect.Type) bool {
	if t.NumMethod() > 0 {
		return true
	}
	return t.Kind() != reflect.Ptr && t.Kind() != reflect.Interface && reflect.PtrTo(t).NumMethod() > 0
}

// fieldSnapshot: the exported scalar fields of a struct (or pointer to one), so Nusantara code can
// read `obj.Name` directly. It is a snapshot; obj.field("Name") always reads the live value.
func fieldSnapshot(v reflect.Value) map[string]interface{} { return fieldSnapshotDepth(v, 0) }

// Scalars always; at the top level also pointer/interface/struct fields as handles (so r.URL.Path,
// resp.Body work) and small maps/slices as data. Nested handles only carry scalars.
func fieldSnapshotDepth(v reflect.Value, depth int) map[string]interface{} {
	e := indirectValue(v)
	if e.Kind() != reflect.Struct {
		return nil
	}
	m := map[string]interface{}{}
	t := e.Type()
	for i := 0; i < t.NumField(); i++ {
		sf := t.Field(i)
		if !sf.IsExported() {
			continue
		}
		fv := e.Field(i)
		switch fv.Kind() {
		case reflect.Bool, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32,
			reflect.Float64, reflect.String:
			m[sf.Name] = encodeOpt(fv, false)
		case reflect.Ptr, reflect.Interface:
			if depth == 0 && !fv.IsNil() && fv.CanInterface() {
				m[sf.Name] = handleRefDepth(fv, depth+1)
			}
		case reflect.Struct:
			if depth == 0 && fv.CanInterface() {
				if hasMethods(fv.Type()) {
					m[sf.Name] = handleRefDepth(fv, depth+1)
				} else {
					m[sf.Name] = encodeOpt(fv, false)
				}
			}
		case reflect.Map, reflect.Slice:
			if depth == 0 && fv.CanInterface() && fv.Len() > 0 && fv.Len() <= 1000 {
				m[sf.Name] = encodeOpt(fv, false)
			}
		}
	}
	return m
}

// handleRef stores v and describes it: "m" = its methods (name -> arity), "f" = scalar field snapshot,
// "d" = its data view when it isn't a pointer ("nilai" on the Nusantara side).
func handleRef(v reflect.Value) map[string]interface{} { return handleRefDepth(v, 0) }

func handleRefDepth(v reflect.Value, depth int) map[string]interface{} {
	ref := map[string]interface{}{"$h": newHandle(v), "tipe": v.Type().String(), "m": methodTable(v.Type())}
	if f := fieldSnapshotDepth(v, depth); len(f) > 0 {
		ref["f"] = f
	}
	if k := v.Kind(); k != reflect.Ptr && k != reflect.Func && k != reflect.Chan && k != reflect.Interface {
		ref["d"] = encodeOpt(v, false)
	}
	return ref
}

// ----------------------------------------------------------------- encode ----

const maxSafeInt = 1 << 53

// encode turns a Go value into something encoding/json can marshal for the Nusantara side.
func encode(v reflect.Value) interface{} { return encodeOpt(v, true) }

// encodeOpt: with methodsAsHandle, a value whose type has methods (time.Time, url.Values, ...)
// becomes a handle so those methods stay callable; without it, just its data.
func encodeOpt(v reflect.Value, methodsAsHandle bool) interface{} {
	if !v.IsValid() {
		return nil
	}
	if !v.CanInterface() {
		return nil
	}
	if methodsAsHandle {
		switch v.Kind() {
		case reflect.Interface, reflect.Ptr, reflect.Func, reflect.Chan:
		default:
			if hasMethods(v.Type()) {
				return handleRef(v)
			}
		}
	}
	switch v.Kind() {
	case reflect.Bool:
		return v.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16,)NSGO"
         R"NSGO( reflect.Int32, reflect.Int64:
		n := v.Int()
		if n > maxSafeInt || n < -maxSafeInt {
			return strconv.FormatInt(n, 10)
		}
		return n
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		n := v.Uint()
		if n > maxSafeInt {
			return strconv.FormatUint(n, 10)
		}
		return n
	case reflect.Float32, reflect.Float64:
		f := v.Float()
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return nil
		}
		return f
	case reflect.String:
		return v.String()
	case reflect.Slice, reflect.Array:
		if v.Kind() == reflect.Slice && v.IsNil() {
			return []interface{}{}
		}
		if v.Type().Elem().Kind() == reflect.Uint8 {
			b := make([]byte, v.Len())
			reflect.Copy(reflect.ValueOf(b), v)
			return string(b)
		}
		out := make([]interface{}, v.Len())
		for i := range out {
			out[i] = encode(v.Index(i))
		}
		return out
	case reflect.Map:
		if v.IsNil() {
			return map[string]interface{}{}
		}
		out := make(map[string]interface{}, v.Len())
		iter := v.MapRange()
		for iter.Next() {
			out[fmt.Sprint(iter.Key().Interface())] = encode(iter.Value())
		}
		return out
	case reflect.Struct:
		if b, err := json.Marshal(v.Interface()); err == nil {
			return json.RawMessage(b)
		}
		p := reflect.New(v.Type())
		p.Elem().Set(v)
		return handleRef(p)
	case reflect.Ptr:
		if v.IsNil() {
			return nil
		}
		switch v.Elem().Kind() {
		case reflect.Bool, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32,
			reflect.Float64, reflect.String:
			return encode(v.Elem())
		}
		return handleRef(v)
	case reflect.Interface:
		if v.IsNil() {
			return nil
		}
		return encode(v.Elem())
	default: // func, chan, unsafe pointer, complex
		if v.Kind() == reflect.Func || v.Kind() == reflect.Chan {
			if v.IsNil() {
				return nil
			}
		}
		return handleRef(v)
	}
}

// ---------------------------------------------------------------- decode ----

var (
	ctxType         = reflect.TypeOf((*context.Context)(nil)).Elem()
	errType         = reflect.TypeOf((*error)(nil)).Elem()
	textUnmarshaler = reflect.TypeOf((*encoding.TextUnmarshaler)(nil)).Elem()
)

func decodeError(t reflect.Type, why string) error {
	return fmt.Errorf("argumen untuk tipe %s: %s", t, why)
}

// convertArg builds a Go value of type t from the JSON the Nusantara side sent.
func convertArg(raw json.RawMessage, t reflect.Type) (reflect.Value, error) {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" || trimmed == "null" {
		if t == ctxType {
			return reflect.ValueOf(context.Background()), nil
		}
		return reflect.Zero(t), nil
	}
	// handle reference / callback marker
	if strings.HasPrefix(trimmed, "{") {
		var marker struct {
			H  string `json:"$h"`
			Cb string `json:"$cb"`
		}
		if err := json.Unmarshal(raw, &marker); err == nil {
			if marker.H != "" {
				hv, ok := lookupHandle(marker.H)
				if !ok {
					return reflect.Value{}, fmt.Errorf("handle %s sudah dibebaskan atau tidak ada", marker.H)
				}
				return adaptHandle(hv, t)
			}
			if marker.Cb != "" && t.Kind() == reflect.Interface {
				if v, ok := adaptCallbackToInterface(t, marker.Cb); ok {
					return v, nil
				}
			}
			if marker.Cb != "" {
				if t.Kind() != reflect.Func {
					return reflect.Value{}, decodeError(t, "callback hanya bisa dikirim ke parameter bertipe fungsi")
				}
				return makeCallback(t, marker.Cb), nil
			}
		}
	}
	if t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Uint8 && strings.HasPrefix(trimmed, "\"") {
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return reflect.Value{}, err
		}
		return reflect.ValueOf([]byte(s)).Convert(t), nil
	}
	if strings.HasPrefix(trimmed, "\"") && reflect.PtrTo(t).Implements(textUnmarshaler) && t.Kind() != reflect.String {
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return reflect.Value{}, err
		}
		p := reflect.New(t)
		if err := p.Interface().(encoding.TextUnmarshaler).UnmarshalText([]byte(s)); err != nil {
			return reflect.Value{}, err
		}
		return p.Elem(), nil
	}
	if t.Kind() == reflect.Interface {
		if t.NumMethod() == 0 {
			var generic interface{}
			if err := json.Unmarshal(raw, &generic); err != nil {
				return reflect.Value{}, err
			}
			return reflect.ValueOf(generic), nil
		}
		return reflect.Value{}, decodeError(t, "butuh handle objek Go, bukan data JSON")
	}
	p := reflect.New(t)
	if err := json.Unmarshal(raw, p.Interface()); err != nil {
		return reflect.Value{}, decodeError(t, err.Error())
	}
	return p.Elem(), nil
}

// adaptHandle fits a stored value to a parameter type (dereferencing or taking an address as needed).
func adaptHandle(hv reflect.Value, t reflect.Type) (reflect.Value, error) {
	if hv.Type().AssignableTo(t) {
		return hv, nil
	}
	if hv.Kind() == reflect.Ptr && !hv.IsNil() && hv.Elem().Type().AssignableTo(t) {
		return hv.Elem(), nil
	}
	if t.Kind() == reflect.Ptr && hv.Type().AssignableTo(t.Elem()) {
		p := reflect.New(t.Elem())
		p.Elem().Set(hv)
		return p, nil
	}
	if hv.Type().ConvertibleTo(t) && hv.Kind() != reflect.Ptr && t.Kind() != reflect.Interface {
		return hv.Convert(t), nil
	}
	return reflect.Value{}, fmt.Errorf("handle bertipe %s tidak cocok untuk parameter bertipe %s", hv.Type(), t)
}

// ------------------------------------------------------------- callbacks ----

type eventQueue struct{ ch chan string }

var (
	qmu    sync.Mutex
	queues = map[string]*eventQueue{}
)

func queueFor(name string) *eventQueue {
	qmu.Lock()
	defer qmu.Unlock()
	q, ok := queues[name]
	if !ok {
		q = &eventQueue{ch: make(chan string, 8192)}
		queues[name] = q
	}
	return q
}

func (q *eventQueue) push(s string) {
	for {
		select {
		case q.ch <- s:
			return
		default:
			select { // full: drop the oldest event rather than block Go's own goroutines
			case <-q.ch:
			default:
			}
		}
	}
}

var (
	replyMu  sync.Mutex
	replies  = map[int64]chan string{}
	replySeq int64
)

// syncCallback: a callback that returns values, or takes an object/pointer (an http handler's
// writer and request, a gin context), must finish on the Nusantara side before Go continues.
// Plain event handlers (func(evt interface{})) stay fire-and-forget.
func syncCallback(t reflect.Type) bool {
	if t.NumOut() > 0 {
		return true
	}
	for i := 0; i < t.NumIn(); i++ {
		in := t.In(i)
		if in.Kind() == reflect.Ptr || (in.Kind() == reflect.Interface && in.NumMethod() > 0) {
			return true
		}
	}
	return false
}

// makeCallback builds a Go func of type t that turns each call into a queued event.
func makeCallback(t reflect.Type, queue string) reflect.Value {
	q := queueFor(queue)
	sync := syncCallback(t)
	return reflect.MakeFunc(t, func(args []reflect.Value) []reflect.Value {
		enc := make([]interface{}, len(args))
		for i, a := range args {
			enc[i] = encode(a)
		}
		outs := make([]reflect.Value, t.NumOut())
		for i := range outs {
			outs[i] = reflect.Zero(t.Out(i))
		}
		if !sync {
			if b, err := json.Marshal(enc); err == nil {
				q.push(string(b))
			}
			return outs
		}
		id := atomic.AddInt64(&replySeq, 1)
		ch := make(chan string, 1)
		replyMu.Lock()
		replies[id] = ch
		replyMu.Unlock()
		defer func() {
			replyMu.Lock()
			delete(replies, id)
			replyMu.Unlock()
		}()
		b, err := json.Marshal(map[string]interface{}{"$id": id, "a": enc})
		if err != nil {
			return outs
		}
		q.push(string(b))
		select {
		case r := <-ch:
			var reply struct {
				R json.RawMessage `json:"r"`
			}
			if json.Unmarshal([]byte(r), &reply) != nil || len(outs) == 0 {
				return outs
			}
			if len(outs) == 1 {
				if v, err := convertArg(reply.R, t.Out(0)); err == nil {
					outs[0] = v
				}
				return outs
			}
			var parts []json.RawMessage
			if json.Unmarshal(reply.R, &parts) == nil {
				for i := range outs {
					if i < len(parts) {
						if v, err := convertArg(parts[i], t.Out(i)); err == nil {
							outs[i] = v
						}
					}
				}
			}
		case <-time.After(60 * time.Second):
		}
		return outs
	})
}

fun)NSGO"
         R"NSGO(c deliverReply(id int64, payload string) {
	replyMu.Lock()
	ch := replies[id]
	replyMu.Unlock()
	if ch != nil {
		select {
		case ch <- payload:
		default:
		}
	}
}

// adaptCallbackToInterface lets a Nusantara function stand in for the few interfaces that std
// packages wrap functions into (http.HandlerFunc and friends).
func adaptCallbackToInterface(t reflect.Type, queue string) (reflect.Value, bool) {
	switch t {
	case handlerType:
		fn := makeCallback(reflect.TypeOf(func(http.ResponseWriter, *http.Request) {}), queue).Interface().(func(http.ResponseWriter, *http.Request))
		return reflect.ValueOf(http.HandlerFunc(fn)), true
	case writerType:
		fn := makeCallback(reflect.TypeOf(func([]byte) (int, error) { return 0, nil }), queue).Interface().(func([]byte) (int, error))
		return reflect.ValueOf(writerFunc(fn)), true
	case stringerType:
		fn := makeCallback(reflect.TypeOf(func() string { return "" }), queue).Interface().(func() string)
		return reflect.ValueOf(stringerFunc(fn)), true
	}
	return reflect.Value{}, false
}

type writerFunc func([]byte) (int, error)

func (f writerFunc) Write(p []byte) (int, error) { return f(p) }

type stringerFunc func() string

func (f stringerFunc) String() string { return f() }

var (
	handlerType  = reflect.TypeOf((*http.Handler)(nil)).Elem()
	writerType   = reflect.TypeOf((*io.Writer)(nil)).Elem()
	stringerType = reflect.TypeOf((*fmt.Stringer)(nil)).Elem()
)

// ----------------------------------------------------------------- calls ----

type callResult struct {
	Values []interface{}
	Err    error
}

func invoke(fv reflect.Value, rawArgs []json.RawMessage) (res callResult) {
	defer func() {
		if r := recover(); r != nil {
			res = callResult{Err: fmt.Errorf("panic di Go: %v", r)}
		}
	}()
	t := fv.Type()
	nIn := t.NumIn()
	variadic := t.IsVariadic()
	fixed := nIn
	if variadic {
		fixed = nIn - 1
	}
	if len(rawArgs) < fixed || (!variadic && len(rawArgs) > fixed) {
		return callResult{Err: fmt.Errorf("butuh %d argumen, dapat %d", fixed, len(rawArgs))}
	}
	in := make([]reflect.Value, 0, len(rawArgs))
	var outs []reflect.Value // {"$ptr": kind} arguments: pointers Go fills in (rows.Scan(&x))
	for i, raw := range rawArgs {
		var pt reflect.Type
		if i < fixed {
			pt = t.In(i)
		} else {
			pt = t.In(nIn - 1).Elem()
		}
		if pv, ok := pointerArg(raw, pt); ok {
			outs = append(outs, pv)
			in = append(in, pv)
			continue
		}
		v, err := convertArg(raw, pt)
		if err != nil {
			return callResult{Err: fmt.Errorf("argumen ke-%d: %w", i+1, err)}
		}
		in = append(in, v)
	}
	var out []reflect.Value
	if variadic {
		out = fv.Call(in)
	} else {
		out = fv.Call(in)
	}
	n := len(out)
	if n > 0 && t.Out(n-1) == errType {
		if e := out[n-1]; !e.IsNil() {
			return callResult{Err: e.Interface().(error)}
		}
		n--
	}
	vals := make([]interface{}, n)
	for i := 0; i < n; i++ {
		vals[i] = encode(out[i])
	}
	if len(outs) > 0 {
		filled := make([]interface{}, len(outs))
		for i, p := range outs {
			filled[i] = encode(p.Elem())
			if e := p.Elem(); e.Kind() == reflect.Slice && e.Type().Elem().Kind() == reflect.Uint8 {
				filled[i] = string(e.Bytes())
			}
		}
		vals = append(vals, filled)
	}
	return callResult{Values: vals}
}

func envelope(v interface{}, err error) string {
	var m map[string]interface{}
	if err != nil {
		m = map[string]interface{}{"err": err.Error()}
	} else {
		m = map[string]interface{}{"ok": v}
	}
	b, e := json.Marshal(m)
	if e != nil {
		b, _ = json.Marshal(map[string]interface{}{"err": "gagal meng-encode hasil: " + e.Error()})
	}
	return string(b)
}

func resultValue(r callResult) interface{} {
	switch len(r.Values) {
	case 0:
		return nil
	case 1:
		return r.Values[0]
	default:
		return r.Values
	}
}

func parseArgs(argsJSON string) ([]json.RawMessage, error) {
	if strings.TrimSpace(argsJSON) == "" {
		return nil, nil
	}
	var args []json.RawMessage
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return nil, fmt.Errorf("argumen harus larik JSON: %w", err)
	}
	return args, nil
}

func callTarget(target, name, argsJSON string) string {
	args, err := parseArgs(argsJSON)
	if err != nil {
		return envelope(nil, err)
	}
	if target == "" {
		fv, ok := funcs[name]
		if !ok {
			return envelope(nil, fmt.Errorf("fungsi Go '%s' tidak ada", name))
		}
		r := invoke(fv, args)
		return envelope(resultValue(r), r.Err)
	}
	hv, ok := lookupHandle(target)
	if !ok {
		return envelope(nil, fmt.Errorf("handle %s sudah dibebaskan atau tidak ada", target))
	}
	switch name {
	case "$json":
		b, err := json.Marshal(indirectValue(hv).Interface())
		if err != nil {
			return envelope(nil, err)
		}
		return `{"ok":` + string(b) + `}`
	case "$str":
		return envelope(fmt.Sprint(hv.Interface()), nil)
	case "$tipe":
		return envelope(hv.Type().String(), nil)
	}
	mv := hv.MethodByName(name)
	if !mv.IsValid() && hv.Kind() != reflect.Ptr && hv.Kind() != reflect.Interface {
		p := reflect.New(hv.Type())
		p.Elem().Set(hv)
		mv = p.MethodByName(name)
	}
	if !mv.IsValid() {
		return envelope(nil, fmt.Errorf("tipe %s tidak punya metode '%s'", hv.Type(), name))
	}
	r := invoke(mv, args)
	return envelope(resultValue(r), r.Err)
}

func indirectValue(v reflect.Value) reflect.Value {
	for v.Kind() == reflect.Ptr || v.Kind() == reflect.Interface {
		if v.IsNil() {
			break
		}
		v = v.Elem()
	}
	return v
}

func fieldOf(handle, name string) (reflect.Value, error) {
	hv, ok := lookupHandle(handle)
	if !ok {
		return reflect.Value{}, fmt.Errorf("handle %s sudah dibebaskan atau tidak ada", handle)
	}
	e := indirectValue(hv)
	if e.Kind() != reflect.Struct {
		return reflect.Value{}, fmt.Errorf("%s bukan struct, tidak punya field", hv.Type())
	}
	f := e.FieldByName(name)
	if !f.IsValid() || !f.CanInterface() {
		return reflect.Value{}, fmt.Errorf("tipe %s tidak punya field publik '%s'", e.Type(), name)
	}
	return f, nil
}

func createValue(typeName, jsonInit string) string {
	t, ok := typs[typeName]
	if !ok {
		return envelope(nil, fmt.Errorf("tipe Go '%s' tidak ada", typeName))
	}
	p := reflect.New(t)
	if s := strings.TrimSpace(jsonInit); s != "" && s != "null" {
		if err := json.Unmarshal([]byte(jsonInit), p.Interface()); err != nil {
			return envelope(nil, decodeError(t, err.Error()))
		}
	}
	return envelope(handleRef(p), nil)
}

func manifest() string {
	type fn struct {
		In       int  `json:"masuk"`
		Variadic bool `json:"variadic"`
	}
	out := map[string]interface{}{}
	fs := map[string]fn{}
	for name, v := range funcs {
		fs[name] = fn{In: v.Type().NumIn(), Variadic: v.Type().IsVariadic()}
	}
	out["fungsi"] = fs
	tn := make([]string, 0, len(typs))
	for n := range typs {
		tn = append(tn, n)
	}
	sort.Strings(tn)
	out["tipe"] = tn
	cn := make([]string, 0, len(consts))
	for n := range consts {
		cn = append(cn, n)
	}
	sort.Strings(cn)
	out["konstanta"] = cn
	b, _ := json.Marshal(out)
	return string(b)
}

// ------------------------------------------------------------ ABI entry ----

func argString(argv []C.NsValue, i int) string {
	if i >= len(argv) || nsType(&argv[i]) != C.NS_STRING {
		return ""
	}
	n := int(argv[i].str_len)
	if n < 0 {
		return C.GoString(argv[i].str)
	}
	return C.GoStringN(argv[i].str, C.int(n))
}

func nsType(v *C.NsValue) C.NsType { return v._type }

func retString(s string) C.NsValue {
	cs := C.CString(s)
	defer C.free(unsafe.Pointer(cs))
	return C.make_string(cs, C.int(len(s)))
}

//export nsGoInvoke
func nsGoInvoke(op C.int, argc C.int, argv *C.NsValue) (ret C.NsValue) {
	defer func() {
		if r := recover(); r != nil {
			ret = retString(envelope(nil, fmt.Errorf("panic di jembatan Go: %v", r)))
		}
	}()
	var args []C.NsValue
	if argc > 0 {
		args = unsafe.Slice(argv, int(argc))
	}
	switch op {
	case 0:
		return retString(callTarget(argString(args, 0), argString(args, 1), argString(args, 2)))
	case 1:
		return retString(createValue(argString(args, 0), argString(args, 1)))
	case 2:
		f, err := fieldOf(argString(args, 0), argString(args, 1))
		if err != nil {
			return retString(envelope(nil, err))
		}
		return r)NSGO"
         R"NSGO(etString(envelope(encode(f), nil))
	case 3:
		f, err := fieldOf(argString(args, 0), argString(args, 1))
		if err != nil {
			return retString(envelope(nil, err))
		}
		if !f.CanSet() {
			return retString(envelope(nil, errors.New("field tidak bisa diubah")))
		}
		v, err := convertArg(json.RawMessage(argString(args, 2)), f.Type())
		if err != nil {
			return retString(envelope(nil, err))
		}
		f.Set(v)
		return retString(envelope(nil, nil))
	case 4:
		name := argString(args, 0)
		if v, ok := consts[name]; ok {
			return retString(envelope(encode(reflect.ValueOf(v)), nil))
		}
		if get, ok := vars[name]; ok {
			return retString(envelope(encode(get()), nil))
		}
		return retString(envelope(nil, fmt.Errorf("konstanta/variabel Go '%s' tidak ada", name)))
	case 8:
		n, _ := strconv.ParseInt(argString(args, 0), 10, 64)
		deliverReply(n, argString(args, 1))
		return retString(envelope(nil, nil))
	case 5:
		q := queueFor(argString(args, 0))
		ms := 0
		if len(args) > 1 && nsType(&args[1]) == C.NS_NUMBER {
			ms = int(args[1].number)
		}
		select {
		case s := <-q.ch:
			return retString(s)
		case <-time.After(time.Duration(ms) * time.Millisecond):
			return retString("")
		}
	case 6:
		return retString(manifest())
	case 7:
		hmu.Lock()
		delete(handles, argString(args, 0))
		hmu.Unlock()
		return C.make_null()
	}
	return C.make_null()
}

// pointerArg recognises {"$ptr": "teks"|"angka"|"boolean"|"bytes"|"apa"} and returns a pointer to
// a fresh value of that kind, for parameters typed as an interface (Scan's ...any).
func pointerArg(raw json.RawMessage, pt reflect.Type) (reflect.Value, bool) {
	if pt.Kind() != reflect.Interface || pt.NumMethod() != 0 || !strings.Contains(string(raw), "$ptr") {
		return reflect.Value{}, false
	}
	var m struct {
		P string `json:"$ptr"`
	}
	if json.Unmarshal(raw, &m) != nil || m.P == "" {
		return reflect.Value{}, false
	}
	switch m.P {
	case "teks":
		return reflect.ValueOf(new(string)), true
	case "angka":
		return reflect.ValueOf(new(float64)), true
	case "boolean":
		return reflect.ValueOf(new(bool)), true
	case "bytes":
		return reflect.ValueOf(new([]byte)), true
	case "apa":
		return reflect.ValueOf(new(interface{})), true
	}
	return reflect.Value{}, false
}
)NSGO"
        },
        {"gen/main.go",
         R"NSGO(// Generator for `nusa go add`: reads the exported API of the wrapped Go packages and writes
//
//	registry_gen.go   what exists (functions, types, constants) -- consumed by bridge.go
//	manifest.json     the same, for humans and tooling
//	index.ns          the Nusantara module that exposes it (runtime helpers + one namespace per package)
//
// Usage (run inside the wrapper module):  gen -module M [-blank P]... <import path>...
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type listedPkg struct {
	ImportPath string
	Name       string
	Dir        string
	GoFiles    []string
	CgoFiles   []string
}

type fnInfo struct {
	Name     string
	In       int
	Variadic bool
}

type pkgInfo struct {
	Alias      string // Go import alias inside registry_gen.go
	Namespace  string // name of the Nusantara namespace
	ImportPath string
	Funcs      []fnInfo
	Types      []string
	Consts     []string
	Vars       []string
}

type multiFlag []string

func (m *multiFlag) String() string     { return strings.Join(*m, ",") }
func (m *multiFlag) Set(s string) error { *m = append(*m, s); return nil }

func main() {
	module := flag.String("module", "", "module path (documentation only)")
	var blanks multiFlag
	flag.Var(&blanks, "blank", "package to import for side effects only (e.g. a database driver); repeatable")
	all := flag.Bool("all", false, "include every public sub-package of each given module path")
	flag.Parse()
	if flag.NArg() == 0 {
		fatal("tidak ada paket yang diberikan")
	}
	paths := expandPaths(flag.Args(), *all)
	explicit := map[string]bool{}
	for _, a := range flag.Args() {
		explicit[a] = true
	}

	var pkgs []*pkgInfo
	usedNS := map[string]int{}
	for i, path := range paths {
		if !explicit[path] {
			// expanded sub-package: skip the ones that are not importable libraries
			if !softListable(path) {
				continue
			}
		}
		lp := goList(path)
		info := &pkgInfo{Alias: "pk" + strconv.Itoa(i+1), ImportPath: lp.ImportPath}
		ns := sanitize(lp.Name)
		if n := usedNS[ns]; n > 0 {
			ns = fmt.Sprintf("%s_%d", ns, n+1)
		}
		usedNS[sanitize(lp.Name)]++
		info.Namespace = ns
		fset := token.NewFileSet()
		for _, f := range append(append([]string{}, lp.GoFiles...), lp.CgoFiles...) {
			file, err := parser.ParseFile(fset, filepath.Join(lp.Dir, f), nil, 0)
			if err != nil {
				fatal("parse %s: %v", f, err)
			}
			collect(file, info)
		}
		sort.Slice(info.Funcs, func(a, b int) bool { return info.Funcs[a].Name < info.Funcs[b].Name })
		sort.Strings(info.Types)
		sort.Strings(info.Consts)
		sort.Strings(info.Vars)
		pkgs = append(pkgs, info)
	}

	writeRegistry("registry_gen.go", pkgs, blanks)
	pruneUntilBuilds("registry_gen.go")
	writeManifestAndIndex(*module, pkgs)
	fmt.Printf("registri: %d paket\n", len(pkgs))
}

func fatal(format string, a ...interface{}) {
	fmt.Fprintf(os.Stderr, "gen: "+format+"\n", a...)
	os.Exit(1)
}

var nonIdent = regexp.MustCompile(`[^A-Za-z0-9_]`)

func sanitize(s string) string {
	s = nonIdent.ReplaceAllString(s, "_")
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "p_" + s
	}
	return s
}

// expandPaths adds a module's public sub-packages: always with -all, and also when the module
// root itself has no package (mongo-driver, golang.org/x/...), where the root alone is unusable.
func expandPaths(args []string, all bool) []string {
	var out []string
	seen := map[string]bool{}
	add := func(p string) {
		if !seen[p] {
			seen[p] = true
			out = append(out, p)
		}
	}
	for _, a := range args {
		rootOK := exec.Command("go", "list", a).Run() == nil
		if rootOK {
			add(a)
		}
		if all || !rootOK {
			raw, err := exec.Command("go", "list", a+"/...").Output()
			if err != nil {
				if !rootOK {
					fatal("paket %s tidak ditemukan (go list %s/... gagal)", a, a)
				}
				continue
			}
			n := 0
			for _, line := range strings.Fields(string(raw)) {
				if publicPackage(line) && n < 60 {
					add(line)
					n++
				}
			}
		}
	}
	return out
}

func softListable(path string) bool {
	out, err := exec.Command("go", "list", "-json", path).Output()
	if err != nil {
		return false
	}
	var lp listedPkg
	if json.Unmarshal(out, &lp) != nil {
		return false
	}
	return lp.Name != "main" && len(lp.GoFiles)+len(lp.CgoFiles) > 0
}

func publicPackage(p string) bool {
	for _, bad := range []string{"/internal", "/cmd/", "/examples", "/example", "/testdata", "/test/", "/vendor/", "/tools", "/bench", "/_"} {
		if strings.Contains(p+"/", bad) {
			return false
		}
	}
	return true
}

func goList(path string) listedPkg {
	out, err := exec.Command("go", "list", "-json", path).Output()
	if err != nil {
		var stderr string
		if ee, ok := err.(*exec.ExitError); ok {
			stderr = string(ee.Stderr)
		}
		fatal("go list %s: %v\n%s", path, err, stderr)
	}
	var lp listedPkg
	if err := json.Unmarshal(out, &lp); err != nil {
		fatal("go list %s: %v", path, err)
	}
	if lp.Name == "main" {
		fatal("%s adalah package main -- tidak bisa dipakai sebagai pustaka", path)
	}
	return lp
}

func collect(f *ast.File, info *pkgInfo) {
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Recv != nil || !ast.IsExported(d.Name.Name) || d.Type.TypeParams != nil {
				continue
			}
			n := 0
			for _, field := range d.Type.Params.List {
				if len(field.Names) == 0 {
					n++
				} else {
					n += len(field.Names)
				}
			}
			variadic := false
			if len(d.Type.Params.List) > 0 {
				_, variadic = d.Type.Params.List[len(d.Type.Params.List)-1].Type.(*ast.Ellipsis)
			}
			info.Funcs = append(info.Funcs, fnInfo{Name: d.Name.Name, In: n, Variadic: variadic})
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if !ast.IsExported(s.Name.Name) || s.TypeParams != nil {
						continue
					}
					if _, isIface := s.Type.(*ast.InterfaceType); isIface {
						continue
					}
					info.Types = append(info.Types, s.Name.Name)
				case *ast.ValueSpec:
					for _, n := range s.Names {
						if !ast.IsExported(n.Name) {
							continue
						}
						if d.Tok == token.CONST {
							info.Consts = append(info.Consts, n.Name)
						} else if d.Tok == token.VAR {
							info.Vars = append(info.Vars, n.Name)
						}
					}
				}
			}
		}
	}
}

func writeRegistry(path string, pkgs []*pkgInfo, blanks []string) {
	var b bytes.Buffer
	b.WriteString("// Code generated by `nusa go add`. DO NOT EDIT.\n\npackage main\n\nimport (\n\t\"reflect\"\n")
	for _, p := range pkgs {
		if len(p.Funcs)+len(p.Types)+len(p.Consts)+len(p.Vars) == 0 {
			fmt.Fprintf(&b, "\t_ %q\n", p.ImportPath)
		} else {
			fmt.Fprintf(&b, "\t%s %q\n", p.Alias, p.ImportPath)
		}
	}
	for _, bl := range blanks {
		fmt.Fprintf(&b, "\t_ %q\n", bl)
	}
	b.WriteString(")\n\n")
	// One entry per line: pruneUntilBuilds removes a line the compiler rejects.
	b.WriteString("var funcs = map[string]reflect.Value{\n")
	for _, p := range pkgs {
		for _, f := range p.Funcs {
			fmt.Fprintf(&b, "\t%q: reflect.ValueOf(%s.%s),\n", p.Namespace+"."+f.Name, p.Alias, f.Name)
		}
	}
	b.WriteString("}\n\nvar typs = map[string]reflect.Type{\n")
	for _, p := range pkgs {
		for _, t := range p.Types {
			fmt.Fprintf(&b, "\t%q: reflect.TypeOf((*%s.%s)(nil)).Elem(),\n", p.Namespace+"."+t, p.Alias, t)
		}
	}
	b.WriteString("}\n\nvar consts = map[string]interface{}{\n")
	for _, p := range pkgs {
		for _, c := range p.Consts {
			fmt.Fprintf(&b, "\t%q: interface{}(%s.%s),\n", p.Namespace+"."+c, p.Alias, c)
		}
	}
	b.WriteString("}\n\n// Package variables are read through a closure so each access sees the current value.\nvar vars = map[string]func() reflect.Value{\n")
	for _, p := range pkgs {
		for _, v := range p.Vars {
			fmt.Fprintf(&b, "\t%q: func() reflect.Value { return reflect.ValueOf(&%s.%s).Elem() },\n", p.Namespace+"."+v, p.Alias, v)
		}
	}
	b.WriteString("}\n")
	if err := os.WriteFile(path, b.Bytes(), 0o644); err != nil {
		fatal("tulis %s: %v", path)NSGO"
         R"NSGO(, err)
	}
}

var errLine = regexp.MustCompile(`registry_gen\.go:(\d+):`)

// Some exported names cannot be put in a registry (untyped constants that overflow, names of
// generic-only helpers, ...). Compile, drop the lines the compiler rejects, repeat.
func pruneUntilBuilds(path string) {
	for attempt := 0; attempt < 40; attempt++ {
		cmd := exec.Command("go", "build", "-o", os.DevNull, ".")
		out, err := cmd.CombinedOutput()
		if err == nil {
			return
		}
		bad := map[int]bool{}
		for _, m := range errLine.FindAllStringSubmatch(string(out), -1) {
			n, _ := strconv.Atoi(m[1])
			bad[n] = true
		}
		if len(bad) == 0 {
			fatal("kompilasi jembatan gagal:\n%s", out)
		}
		data, _ := os.ReadFile(path)
		lines := strings.Split(string(data), "\n")
		kept := lines[:0:0]
		dropped := 0
		for i, l := range lines {
			if bad[i+1] && strings.HasPrefix(l, "\t\"") {
				dropped++
				continue
			}
			kept = append(kept, l)
		}
		if dropped == 0 {
			fatal("kompilasi jembatan gagal (tidak bisa dipangkas otomatis):\n%s", out)
		}
		fmt.Printf("  melewati %d nama yang tidak bisa dijembatani\n", dropped)
		_ = os.WriteFile(path, []byte(strings.Join(kept, "\n")), 0o644)
	}
	fatal("terlalu banyak percobaan memangkas registri")
}

func writeManifestAndIndex(module string, pkgs []*pkgInfo) {
	manifest := map[string]interface{}{"modul": module}
	pm := map[string]interface{}{}
	for _, p := range pkgs {
		pm[p.Namespace] = map[string]interface{}{"import": p.ImportPath, "fungsi": p.Funcs, "tipe": p.Types, "konstanta": p.Consts, "variabel": p.Vars}
	}
	manifest["paket"] = pm
	b, _ := json.MarshalIndent(manifest, "", "  ")
	_ = os.WriteFile("manifest.json", b, 0o644)

	var s strings.Builder
	s.WriteString("// GENERATED by `nusa go add` -- jangan diedit manual.\n")
	fmt.Fprintf(&s, "// Jembatan ke modul Go: %s\n", module)
	s.WriteString("// plugin.so di folder ini sudah hasil build: MENJALANKAN modul ini TIDAK butuh Go terpasang.\n\n")
	s.WriteString(nsRuntime)
	s.WriteString("\n")
	for _, p := range pkgs {
		fmt.Fprintf(&s, "// ---- paket %s (%s) ----\nbuat %s = peta_baru();\n", p.Namespace, p.ImportPath, p.Namespace)
		for _, f := range p.Funcs {
			fixed := f.In
			if f.Variadic {
				fixed--
			}
			params := make([]string, 0, f.In)
			for i := 0; i < fixed; i++ {
				params = append(params, "a"+strconv.Itoa(i))
			}
			args := "[" + strings.Join(params, ", ") + "]"
			if f.Variadic {
				params = append(params, "resto")
				args = "_gabung_arg(" + args + ", resto)"
			}
			fmt.Fprintf(&s, "%s[%q] = fungsi(%s) { hasil _panggil(\"\", %q, %s); };\n",
				p.Namespace, f.Name, strings.Join(params, ", "), p.Namespace+"."+f.Name, args)
		}
		for _, t := range p.Types {
			fmt.Fprintf(&s, "%s[%q] = fungsi(data) { hasil _buat(%q, data); };\n", p.Namespace, t, p.Namespace+"."+t)
		}
		for _, c := range p.Consts {
			fmt.Fprintf(&s, "%s[%q] = _konst(%q);\n", p.Namespace, c, p.Namespace+"."+c)
		}
		for _, v := range p.Vars {
			fmt.Fprintf(&s, "%s[%q] = _konst(%q);\n", p.Namespace, v, p.Namespace+"."+v)
		}
		s.WriteString("\n")
	}
	_ = os.WriteFile("index.ns", []byte(s.String()), 0o644)
}

// Runtime helpers of the generated module (brace syntax, so it doesn't depend on layout rules).
const nsRuntime = `buat _p = muat_plugin("./plugin.so");
buat _no_cb = 0;
buat _aktif = benar;

fungsi _urai(teks_json) {
    buat r = json_decode(teks_json);
    jika r["err"] != kosong { lempar r["err"]; }
    hasil _bungkus(r["ok"]);
}

fungsi _bungkus(v) {
    buat t = tipe(v);
    jika t == "larik" {
        buat keluar = [];
        untuk (buat i = 0; i < panjang(v); i = i + 1) { tambah(keluar, _bungkus(v[i])); }
        hasil keluar;
    }
    jika t == "peta" {
        jika v["$h"] != kosong { hasil _objek(v); }
        buat keluar = peta_baru();
        buat kunci = peta_kunci(v);
        untuk (buat i = 0; i < panjang(kunci); i = i + 1) { keluar[kunci[i]] = _bungkus(v[kunci[i]]); }
        hasil keluar;
    }
    hasil v;
}

fungsi _lepas(v) {
    buat t = tipe(v);
    jika t == "fungsi" { hasil _callback(v); }
    jika t == "larik" {
        buat keluar = [];
        untuk (buat i = 0; i < panjang(v); i = i + 1) { tambah(keluar, _lepas(v[i])); }
        hasil keluar;
    }
    jika t == "peta" {
        buat keluar = peta_baru();
        jika v["$h"] != kosong { keluar["$h"] = v["$h"]; hasil keluar; }
        buat kunci = peta_kunci(v);
        untuk (buat i = 0; i < panjang(kunci); i = i + 1) { keluar[kunci[i]] = _lepas(v[kunci[i]]); }
        hasil keluar;
    }
    hasil v;
}

// Penunjuk keluaran buat parameter seperti rows.Scan(...any): jenis "teks", "angka", "boolean",
// "bytes" atau "apa". Go mengisinya, dan pemanggilnya mengembalikan larik nilai yang terisi.
fungsi penunjuk(k) {
    buat p = peta_baru();
    p["$ptr"] = k;
    hasil p;
}

fungsi _gabung_arg(dasar, resto) {
    jika resto != kosong {
        untuk (buat i = 0; i < panjang(resto); i = i + 1) { tambah(dasar, resto[i]); }
    }
    hasil dasar;
}

fungsi _panggil(target, nama, args) {
    buat lepas = [];
    untuk (buat i = 0; i < panjang(args); i = i + 1) { tambah(lepas, _lepas(args[i])); }
    hasil _urai(_p.panggil(target, nama, json_encode(lepas)));
}

fungsi _buat(tipe_go, data) {
    jika data == kosong { hasil _urai(_p.buat(tipe_go, "")); }
    hasil _urai(_p.buat(tipe_go, json_encode(_lepas(data))));
}

fungsi _konst(nama) { hasil _urai(_p.konst(nama)); }

fungsi _metode(h, nama, jumlah) {
    // 100+n: metode variadik -- n argumen tetap lalu satu larik untuk sisanya.
    jika jumlah == 100 { hasil fungsi(r) { hasil _panggil(h, nama, _gabung_arg([], r)); }; }
    jika jumlah == 101 { hasil fungsi(a, r) { hasil _panggil(h, nama, _gabung_arg([a], r)); }; }
    jika jumlah == 102 { hasil fungsi(a, b, r) { hasil _panggil(h, nama, _gabung_arg([a, b], r)); }; }
    jika jumlah == 103 { hasil fungsi(a, b, c, r) { hasil _panggil(h, nama, _gabung_arg([a, b, c], r)); }; }
    jika jumlah == 104 { hasil fungsi(a, b, c, d, r) { hasil _panggil(h, nama, _gabung_arg([a, b, c, d], r)); }; }
    jika jumlah == 0 { hasil fungsi() { hasil _panggil(h, nama, []); }; }
    jika jumlah == 1 { hasil fungsi(a) { hasil _panggil(h, nama, [a]); }; }
    jika jumlah == 2 { hasil fungsi(a, b) { hasil _panggil(h, nama, [a, b]); }; }
    jika jumlah == 3 { hasil fungsi(a, b, c) { hasil _panggil(h, nama, [a, b, c]); }; }
    jika jumlah == 4 { hasil fungsi(a, b, c, d) { hasil _panggil(h, nama, [a, b, c, d]); }; }
    jika jumlah == 5 { hasil fungsi(a, b, c, d, e) { hasil _panggil(h, nama, [a, b, c, d, e]); }; }
    jika jumlah == 6 { hasil fungsi(a, b, c, d, e, f) { hasil _panggil(h, nama, [a, b, c, d, e, f]); }; }
    jika jumlah == 7 { hasil fungsi(a, b, c, d, e, f, g) { hasil _panggil(h, nama, [a, b, c, d, e, f, g]); }; }
    jika jumlah == 8 { hasil fungsi(a, b, c, d, e, f, g, i) { hasil _panggil(h, nama, [a, b, c, d, e, f, g, i]); }; }
    // Lebih dari 8 argumen: satu parameter larik berisi semua argumen.
    hasil fungsi(semua) { hasil _panggil(h, nama, semua); };
}

fungsi _objek(v) {
    buat o = peta_baru();
    buat h = v["$h"];
    o["$h"] = h;
    o["$g"] = pegang(_p.bebas, h);
    o["tipe"] = v["tipe"];
    buat daftar = v["m"];
    buat nama = peta_kunci(daftar);
    untuk (buat i = 0; i < panjang(nama); i = i + 1) { o[nama[i]] = _metode(h, nama[i], daftar[nama[i]]); }
    jika v["f"] != kosong {
        buat kf = peta_kunci(v["f"]);
        untuk (buat i = 0; i < panjang(kf); i = i + 1) { o[kf[i]] = _bungkus(v["f"][kf[i]]); }
    }
    jika v["d"] != kosong { o["nilai"] = _bungkus(v["d"]); }
    o["json"] = fungsi() { hasil _urai(_p.panggil(h, "$json", "[]")); };
    o["teks"] = fungsi() { hasil _urai(_p.panggil(h, "$str", "[]")); };
    o["field"] = fungsi(n) { hasil _urai(_p.field(h, n)); };
    o["set"] = fungsi(n, x) { hasil _urai(_p.set_field(h, n, json_encode(_lepas(x)))); };
    o["bebas"] = fungsi() { _p.bebas(h); };
    hasil o;
}

fungsi _picu(f, a) {
    buat n = panjang(a);
    jika n == 0 { hasil f(); }
    jik)NSGO"
         R"NSGO(a n == 1 { hasil f(_bungkus(a[0])); }
    jika n == 2 { hasil f(_bungkus(a[0]), _bungkus(a[1])); }
    jika n == 3 { hasil f(_bungkus(a[0]), _bungkus(a[1]), _bungkus(a[2])); }
    jika n == 4 { hasil f(_bungkus(a[0]), _bungkus(a[1]), _bungkus(a[2]), _bungkus(a[3])); }
    jika n == 5 { hasil f(_bungkus(a[0]), _bungkus(a[1]), _bungkus(a[2]), _bungkus(a[3]), _bungkus(a[4])); }
    hasil kosong;
}

fungsi _dengarkan(nama, f) {
    jalan(fungsi() {
        latar();
        selama _aktif {
            buat e = _p.event(nama, 500);
            jika e != "" {
                buat d = json_decode(e);
                jika tipe(d) == "peta" {
                    // callback sinkron: Go menunggu hasilnya lewat balas()
                    buat r = kosong;
                    coba { r = _picu(f, d["a"]); } tangkap (err) { cetak("kesalahan di callback:", err); }
                    _p.balas(ke_teks(d["$id"]), json_encode({"r": _lepas(r)}));
                } lain {
                    _picu(f, d);
                }
            }
        }
    });
}

fungsi _callback(f) {
    _no_cb = _no_cb + 1;
    buat nama = "cb" + ke_teks(_no_cb);
    _dengarkan(nama, f);
    buat r = peta_baru();
    r["$cb"] = nama;
    hasil r;
}

// Menghentikan semua pendengar callback (biar proses bisa selesai).
fungsi berhenti_dengarkan() { _aktif = salah; }
`
)NSGO"
        },
    };
    return files;
}

}  // namespace gobridge
