// GENERATED by tools/embed_lib.py from lib/ -- do not edit by hand.
#include <string>
#include <unordered_map>

namespace pystd {

const char* embeddedLibModule(const std::string& name) {
    static const std::unordered_map<std::string, const char*> mods = {
        {"abc",
         R"NSLIB(class ABC:
    pass

ABCMeta = ABC

def abstractmethod(fn):
    return fn

def abstractproperty(fn):
    return fn
)NSLIB"
        },
        {"argparse",
         R"NSLIB(import sys

class ArgumentError(Exception):
    pass

class Namespace:
    def __init__(self, **kw):
        for k in kw:
            setattr(self, k, kw[k])
    def __repr__(self):
        items = []
        for k in vars(self):
            items.append(k + "=" + repr(getattr(self, k)))
        return "Namespace(" + ", ".join(items) + ")"

class ArgumentParser:
    def __init__(self, prog=None, description=None, epilog=None, usage=None, add_help=True, **kw):
        self.prog = prog if prog is not None else (sys.argv[0].split("/")[-1] if len(sys.argv) > 0 else "prog")
        self.description = description
        self.epilog = epilog
        self._positionals = []
        self._optionals = []
        self._add_help = add_help
        self._subparsers = None
    def add_argument(self, *names, **kw):
        spec = {"names": names, "action": kw.get("action", "store"), "type": kw.get("type", None),
                "default": kw.get("default", None), "help": kw.get("help", ""), "nargs": kw.get("nargs", None),
                "choices": kw.get("choices", None), "required": kw.get("required", False),
                "metavar": kw.get("metavar", None), "const": kw.get("const", None)}
        if names[0].startswith("-"):
            dest = kw.get("dest", None)
            if dest is None:
                longs = [n for n in names if n.startswith("--")]
                base = longs[0] if len(longs) > 0 else names[0]
                dest = base.lstrip("-").replace("-", "_")
            spec["dest"] = dest
            if spec["action"] == "store_true":
                spec["default"] = kw.get("default", False)
            elif spec["action"] == "store_false":
                spec["default"] = kw.get("default", True)
            elif spec["action"] == "count":
                spec["default"] = kw.get("default", 0)
            self._optionals.append(spec)
        else:
            spec["dest"] = kw.get("dest", names[0])
            self._positionals.append(spec)
        return spec
    def add_subparsers(self, dest=None, **kw):
        self._subparsers = {"dest": dest, "parsers": {}}
        outer = self
        class _Sub:
            def add_parser(self, name, **kw2):
                p = ArgumentParser(prog=outer.prog + " " + name, **kw2)
                outer._subparsers["parsers"][name] = p
                return p
        return _Sub()
    def add_mutually_exclusive_group(self, **kw):
        return self
    def add_argument_group(self, *a, **kw):
        return self
    def _convert(self, spec, text):
        t = spec["type"]
        if t is not None:
            try:
                v = t(text)
            except Exception:
                self.error("argument " + "/".join(spec["names"]) + ": invalid " + getattr(t, "__name__", "value") + " value: '" + text + "'")
        else:
            v = text
        if spec["choices"] is not None and v not in spec["choices"]:
            self.error("argument " + "/".join(spec["names"]) + ": invalid choice: " + repr(v) + " (choose from " + ", ".join([repr(c) for c in spec["choices"]]) + ")")
        return v
    def format_usage(self):
        parts = ["usage: " + self.prog]
        if self._add_help:
            parts.append("[-h]")
        for o in self._optionals:
            n = o["names"][0]
            if o["action"] in ("store_true", "store_false", "count"):
                parts.append("[" + n + "]")
            else:
                parts.append("[" + n + " " + (o["metavar"] or o["dest"].upper()) + "]")
        for p in self._positionals:
            parts.append(p["metavar"] or p["dest"])
        return " ".join(parts) + "\n"
    def format_help(self):
        out = self.format_usage()
        if self.description:
            out += "\n" + self.description + "\n"
        if len(self._positionals) > 0:
            out += "\npositional arguments:\n"
            for p in self._positionals:
                out += "  " + (p["metavar"] or p["dest"]).ljust(22) + p["help"] + "\n"
        out += "\noptions:\n"
        if self._add_help:
            out += "  -h, --help".ljust(24) + "show this help message and exit\n"
        for o in self._optionals:
            label = ", ".join(o["names"])
            if o["action"] not in ("store_true", "store_false", "count"):
                label += " " + (o["metavar"] or o["dest"].upper())
            out += ("  " + label).ljust(24) + o["help"] + "\n"
        if self.epilog:
            out += "\n" + self.epilog + "\n"
        return out
    def print_help(self):
        sys.stdout.write(self.format_help())
    def print_usage(self):
        sys.stdout.write(self.format_usage())
    def error(self, message):
        sys.stderr.write(self.format_usage())
        sys.stderr.write(self.prog + ": error: " + message + "\n")
        sys.exit(2)
    def exit(self, status=0, message=None):
        if message:
            sys.stderr.write(message)
        sys.exit(status)
    def parse_args(self, args=None):
        ns, rest = self.parse_known_args(args)
        if len(rest) > 0:
            self.error("unrecognized arguments: " + " ".join(rest))
        return ns
    def parse_known_args(self, args=None):
        if args is None:
            args = sys.argv[1:]
        args = list(args)
        ns = Namespace()
        for o in self._optionals:
            setattr(ns, o["dest"], o["default"] if o["action"] != "append" else o["default"])
        for p in self._positionals:
            setattr(ns, p["dest"], p["default"])
        extras = []
        pos_values = []
        i = 0
        only_pos = False
        while i < len(args):
            a = args[i]
            if only_pos or not a.startswith("-") or a == "-" or (a[1:].replace(".", "", 1).isdigit()):
                pos_values.append(a)
                i += 1
                continue
            if a == "--":
                only_pos = True
                i += 1
                continue
            if a in ("-h", "--help") and self._add_help:
                self.print_help()
                sys.exit(0)
            name = a
            inline = None
            if a.startswith("--") and "=" in a:
                name, _, inline = a.partition("=")
            spec = None
            for o in self._optionals:
                if name in o["names"]:
                    spec = o
            if spec is None and a.startswith("--"):
                matches = [o for o in self._optionals if any([n.startswith(name) for n in o["names"] if n.startswith("--")])]
                if len(matches) == 1:
                    spec = matches[0]
            if spec is None and not a.startswith("--") and len(a) > 2:
                for o in self._optionals:
                    if a[:2] in o["names"] and o["action"] not in ("store_true", "store_false", "count"):
                        spec = o
                        inline = a[2:]
            if spec is None:
                extras.append(a)
                i += 1
                continue
            act = spec["action"]
            if act == "store_true":
                setattr(ns, spec["dest"], True)
            elif act == "store_false":
                setattr(ns, spec["dest"], False)
            elif act == "count":
                setattr(ns, spec["dest"], getattr(ns, spec["dest"]) + 1)
            elif act == "store_const":
                setattr(ns, spec["dest"], spec["const"])
            elif act == "version":
                sys.stdout.write(str(spec["default"]) + "\n")
                sys.exit(0)
            else:
                nargs = spec["nargs"]
                if nargs is None:
                    if inline is None:
                        if i + 1 >= len(args):
                            self.error("argument " + "/".join(spec["names"]) + ": expected one argument")
                        i += 1
                        inline = args[i]
                    val = self._convert(spec, inline)
                else:
                    vals = []
                    if inline is not )NSLIB"
         R"NSLIB(None:
                        vals.append(self._convert(spec, inline))
                    while i + 1 < len(args) and not args[i + 1].startswith("-") and (nargs in ("*", "+") or len(vals) < nargs):
                        i += 1
                        vals.append(self._convert(spec, args[i]))
                    if nargs == "+" and len(vals) == 0:
                        self.error("argument " + "/".join(spec["names"]) + ": expected at least one argument")
                    val = vals
                if act == "append":
                    cur = getattr(ns, spec["dest"])
                    if cur is None:
                        cur = []
                    cur.append(val)
                    setattr(ns, spec["dest"], cur)
                else:
                    setattr(ns, spec["dest"], val)
            i += 1
        pi = 0
        if self._subparsers is not None and len(pos_values) > 0 and pos_values[0] in self._subparsers["parsers"]:
            sub = self._subparsers["parsers"][pos_values[0]]
            if self._subparsers["dest"] is not None:
                setattr(ns, self._subparsers["dest"], pos_values[0])
            subns, subextra = sub.parse_known_args(pos_values[1:])
            for k in vars(subns):
                setattr(ns, k, getattr(subns, k))
            extras.extend(subextra)
            pos_values = []
        for p in self._positionals:
            nargs = p["nargs"]
            if nargs in ("*", "+"):
                vals = [self._convert(p, v) for v in pos_values[pi:]]
                if nargs == "+" and len(vals) == 0:
                    self.error("the following arguments are required: " + p["dest"])
                setattr(ns, p["dest"], vals)
                pi = len(pos_values)
            elif nargs == "?":
                if pi < len(pos_values):
                    setattr(ns, p["dest"], self._convert(p, pos_values[pi]))
                    pi += 1
            elif isinstance(nargs, int):
                vals = [self._convert(p, v) for v in pos_values[pi:pi + nargs]]
                setattr(ns, p["dest"], vals)
                pi += nargs
            else:
                if pi >= len(pos_values):
                    self.error("the following arguments are required: " + p["dest"])
                setattr(ns, p["dest"], self._convert(p, pos_values[pi]))
                pi += 1
        extras.extend(pos_values[pi:])
        for o in self._optionals:
            if o["required"] and getattr(ns, o["dest"]) is None:
                self.error("the following arguments are required: " + "/".join(o["names"]))
        return (ns, extras)

class HelpFormatter:
    pass
class RawTextHelpFormatter(HelpFormatter):
    pass
class RawDescriptionHelpFormatter(HelpFormatter):
    pass
class ArgumentDefaultsHelpFormatter(HelpFormatter):
    pass
)NSLIB"
        },
        {"asyncio",
         R"NSLIB(# async def f(): ... becomes  def f(): return _mkco(lambda: ...)  -- a coroutine, started by await / run / create_task.
# Tasks run on goroutines, so gather() and create_task() really overlap while they sleep or wait.
import time

class CancelledError(Exception):
    pass

class TimeoutError(Exception):
    pass

class Coroutine:
    def __init__(self, fn):
        self._fn = fn
        self._used = False
    def _run(self):
        if self._used:
            raise RuntimeError("cannot reuse already awaited coroutine")
        self._used = True
        return self._fn()
    def close(self):
        self._used = True

class Task:
    def __init__(self, coro):
        self._coro = coro
        self._done = kanal_baru(1)
        self._finished = False
        self._result = None
        self._error = None
        self._cancelled = False
    def _main(self):
        try:
            self._result = self._coro._run()
        except Exception as e:
            self._error = e
        self._finished = True
        kanal_tutup(self._done)
    def _start(self):
        me = self
        jalan(lambda: me._main())
    def done(self):
        return self._finished
    def cancelled(self):
        return self._cancelled
    def cancel(self):
        self._cancelled = True
        return not self._finished
    def result(self):
        if not self._finished:
            kanal_terima(self._done)
        if self._error is not None:
            raise self._error
        return self._result
    def exception(self):
        if not self._finished:
            kanal_terima(self._done)
        return self._error
    def add_done_callback(self, fn):
        fn(self)

def _mkco(fn):
    return Coroutine(fn)

def _await(x):
    if isinstance(x, Task):
        return x.result()
    if isinstance(x, Coroutine):
        return x._run()
    if isinstance(x, Future):
        return x.result()
    return x

class Future:
    def __init__(self):
        self._value = None
        self._set = False
        self._error = None
    def set_result(self, v):
        self._value = v
        self._set = True
    def set_exception(self, e):
        self._error = e
        self._set = True
    def done(self):
        return self._set
    def result(self):
        while not self._set:
            tidur(1)
        if self._error is not None:
            raise self._error
        return self._value

def run(coro, debug=None):
    return _await(coro)

def create_task(coro, name=None):
    t = Task(coro)
    t._start()
    return t

ensure_future = create_task

def sleep(delay, result=None):
    tidur(delay * 1000)
    return result

def gather(*aws, return_exceptions=False):
    tasks = []
    for a in aws:
        if isinstance(a, Coroutine):
            tasks.append(create_task(a))
        else:
            tasks.append(a)
    out = []
    for t in tasks:
        if isinstance(t, Task):
            if return_exceptions:
                e = t.exception()
                out.append(e if e is not None else t.result())
            else:
                out.append(t.result())
        else:
            out.append(t)
    return out

def wait_for(aw, timeout=None):
    if timeout is None:
        return _await(aw)
    t = aw if isinstance(aw, Task) else create_task(aw)
    waited = 0.0
    while not t.done():
        tidur(1)
        waited += 0.001
        if waited >= timeout:
            raise TimeoutError("timed out")
    return t.result()

def wait(aws, timeout=None):
    done = [a.result() and a for a in aws]
    return (set(aws), set())

class Lock:
    def __init__(self):
        self._held = False
    def locked(self):
        return self._held
    def acquire(self):
        while self._held:
            tidur(1)
        self._held = True
        return True
    def release(self):
        self._held = False
    def __enter__(self):
        self.acquire()
        return self
    def __exit__(self, a, b, c):
        self.release()
        return False

class Event:
    def __init__(self):
        self._flag = False
    def set(self):
        self._flag = True
    def clear(self):
        self._flag = False
    def is_set(self):
        return self._flag
    def wait(self):
        while not self._flag:
            tidur(1)
        return True

class Semaphore:
    def __init__(self, value=1):
        self._value = value
    def acquire(self):
        while self._value <= 0:
            tidur(1)
        self._value -= 1
        return True
    def release(self):
        self._value += 1
    def __enter__(self):
        self.acquire()
        return self
    def __exit__(self, a, b, c):
        self.release()
        return False

class Queue:
    def __init__(self, maxsize=0):
        self._items = []
        self.maxsize = maxsize
    def put_nowait(self, item):
        self._items.append(item)
    def put(self, item):
        while self.maxsize > 0 and len(self._items) >= self.maxsize:
            tidur(1)
        self._items.append(item)
    def get(self):
        while len(self._items) == 0:
            tidur(1)
        return self._items.pop(0)
    def get_nowait(self):
        return self._items.pop(0)
    def qsize(self):
        return len(self._items)
    def empty(self):
        return len(self._items) == 0

class _Loop:
    def run_until_complete(self, coro):
        return _await(coro)
    def close(self):
        pass
    def create_task(self, coro):
        return create_task(coro)
    def time(self):
        return time.time()

_loop = _Loop()

def get_event_loop():
    return _loop

new_event_loop = get_event_loop
get_running_loop = get_event_loop

def set_event_loop(loop):
    pass
)NSLIB"
        },
        {"bisect",
         R"NSLIB(def bisect_left(a, x, lo=0, hi=None):
    if hi is None:
        hi = len(a)
    while lo < hi:
        mid = (lo + hi) // 2
        if a[mid] < x:
            lo = mid + 1
        else:
            hi = mid
    return lo

def bisect_right(a, x, lo=0, hi=None):
    if hi is None:
        hi = len(a)
    while lo < hi:
        mid = (lo + hi) // 2
        if x < a[mid]:
            hi = mid
        else:
            lo = mid + 1
    return lo

bisect = bisect_right

def insort_left(a, x, lo=0, hi=None):
    a.insert(bisect_left(a, x, lo, hi), x)

def insort_right(a, x, lo=0, hi=None):
    a.insert(bisect_right(a, x, lo, hi), x)

insort = insort_right
)NSLIB"
        },
        {"collections",
         R"NSLIB(def defaultdict(factory=None, init=None):
    d = _defaultdict(factory)
    if init is not None:
        d.update(init)
    return d

def Counter(items=None, **kw):
    c = _defaultdict(int)
    if items is not None:
        if isinstance(items, dict):
            for k in items:
                c[k] = items[k]
        else:
            for x in items:
                c[x] = c[x] + 1
    for k in kw:
        c[k] = kw[k]
    return c

def OrderedDict(items=None):
    d = {}
    if items is not None:
        d.update(items)
    return d

def namedtuple(typename, field_names, defaults=None):
    return _namedtuple(typename, field_names)

class deque:
    def __init__(self, iterable=None, maxlen=None):
        self._d = list(iterable) if iterable is not None else []
        self.maxlen = maxlen
        self._trim(True)
    def _trim(self, left):
        if self.maxlen is not None:
            while len(self._d) > self.maxlen:
                if left:
                    self._d.pop(0)
                else:
                    self._d.pop()
    def append(self, x):
        self._d.append(x)
        self._trim(True)
    def appendleft(self, x):
        self._d.insert(0, x)
        self._trim(False)
    def pop(self):
        if len(self._d) == 0:
            raise IndexError("pop from an empty deque")
        return self._d.pop()
    def popleft(self):
        if len(self._d) == 0:
            raise IndexError("pop from an empty deque")
        return self._d.pop(0)
    def extend(self, it):
        for x in it:
            self.append(x)
    def extendleft(self, it):
        for x in it:
            self.appendleft(x)
    def clear(self):
        self._d = []
    def rotate(self, n=1):
        k = len(self._d)
        if k == 0:
            return
        n = n % k
        if n:
            self._d = self._d[-n:] + self._d[:-n]
    def count(self, x):
        return self._d.count(x)
    def remove(self, x):
        self._d.remove(x)
    def reverse(self):
        self._d.reverse()
    def index(self, x):
        return self._d.index(x)
    def copy(self):
        return deque(self._d, self.maxlen)
    def __len__(self):
        return len(self._d)
    def __getitem__(self, i):
        return self._d[i]
    def __iter__(self):
        return iter(self._d)
    def __contains__(self, x):
        return x in self._d
    def __str__(self):
        return "deque(" + str(self._d) + ")"
    def __repr__(self):
        return "deque(" + str(self._d) + ")"
    def __eq__(self, o):
        return isinstance(o, deque) and self._d == o._d
)NSLIB"
        },
        {"contextlib",
         R"NSLIB(class _GeneratorContextManager:
    def __init__(self, gen):
        self._gen = gen
    def __enter__(self):
        return next(self._gen)
    def __exit__(self, t, value, tb):
        if value is None:
            try:
                next(self._gen)
            except StopIteration:
                return False
            return False
        try:
            self._gen.throw_(value)
        except StopIteration:
            return True
        except Exception as e:
            if e is value:
                return False
            raise
        return True

def contextmanager(fn):
    def helper(*args, **kw):
        return _GeneratorContextManager(fn(*args, **kw))
    return helper

class suppress:
    def __init__(self, *exceptions):
        self._exc = exceptions
    def __enter__(self):
        return None
    def __exit__(self, t, value, tb):
        if value is None:
            return False
        for cls in self._exc:
            if isinstance(value, cls):
                return True
        return False

class closing:
    def __init__(self, thing):
        self.thing = thing
    def __enter__(self):
        return self.thing
    def __exit__(self, a, b, c):
        self.thing.close()
        return False

class nullcontext:
    def __init__(self, enter_result=None):
        self.enter_result = enter_result
    def __enter__(self):
        return self.enter_result
    def __exit__(self, a, b, c):
        return False

class ExitStack:
    def __init__(self):
        self._cbs = []
    def enter_context(self, cm):
        r = cm.__enter__()
        self._cbs.append(cm)
        return r
    def callback(self, fn, *args, **kw):
        self._cbs.append(lambda: fn(*args, **kw))
    def __enter__(self):
        return self
    def __exit__(self, a, b, c):
        for cm in reversed(self._cbs):
            if callable(cm):
                cm()
            else:
                cm.__exit__(None, None, None)
        return False
)NSLIB"
        },
        {"csv",
         R"NSLIB(QUOTE_MINIMAL = 0
QUOTE_ALL = 1
QUOTE_NONNUMERIC = 2
QUOTE_NONE = 3

class Error(Exception):
    pass

def _parse_line(line, delimiter, quotechar):
    row = []
    field = ""
    inq = False
    i = 0
    n = len(line)
    while i < n:
        c = line[i]
        if inq:
            if c == quotechar:
                if i + 1 < n and line[i + 1] == quotechar:
                    field += quotechar
                    i += 1
                else:
                    inq = False
            else:
                field += c
        else:
            if c == quotechar:
                inq = True
            elif c == delimiter:
                row.append(field)
                field = ""
            else:
                field += c
        i += 1
    row.append(field)
    return row

def _lines(source):
    if isinstance(source, str):
        return source.split("\n")
    if hasattr(source, "read"):
        return source.read().split("\n")
    return list(source)

def reader(source, delimiter=",", quotechar='"', **kw):
    pending = ""
    for raw in _lines(source):
        line = raw.rstrip("\r\n")
        if pending != "":
            line = pending + "\n" + line
            pending = ""
        if line.count(quotechar) % 2 == 1:
            pending = line
            continue
        if line == "":
            continue
        yield _parse_line(line, delimiter, quotechar)
    if pending != "":
        yield _parse_line(pending, delimiter, quotechar)

class DictReader:
    def __init__(self, source, fieldnames=None, delimiter=",", quotechar='"', **kw):
        self._rows = list(reader(source, delimiter, quotechar))
        if fieldnames is None:
            self.fieldnames = self._rows[0] if self._rows else []
            self._rows = self._rows[1:]
        else:
            self.fieldnames = fieldnames
    def __iter__(self):
        out = []
        for r in self._rows:
            d = {}
            for i in range(len(self.fieldnames)):
                d[self.fieldnames[i]] = r[i] if i < len(r) else None
            out.append(d)
        return iter(out)

def _quote(v, delimiter, quotechar, quoting):
    s = "" if v is None else str(v)
    need = quoting == 1 or delimiter in s or quotechar in s or "\n" in s or "\r" in s
    if quoting == 2 and not isinstance(v, (int, float)):
        need = True
    if need and quoting != 3:
        return quotechar + s.replace(quotechar, quotechar + quotechar) + quotechar
    return s

class writer:
    def __init__(self, target, delimiter=",", quotechar='"', quoting=0, lineterminator="\n", **kw):
        self._t = target
        self._d = delimiter
        self._q = quotechar
        self._quoting = quoting
        self._lt = lineterminator
    def writerow(self, row):
        line = self._d.join([_quote(v, self._d, self._q, self._quoting) for v in row]) + self._lt
        self._t.write(line)
        return len(line)
    def writerows(self, rows):
        for r in rows:
            self.writerow(r)

class DictWriter:
    def __init__(self, target, fieldnames, delimiter=",", quotechar='"', quoting=0, lineterminator="\n", **kw):
        self._w = writer(target, delimiter, quotechar, quoting, lineterminator)
        self.fieldnames = fieldnames
    def writeheader(self):
        self._w.writerow(self.fieldnames)
    def writerow(self, d):
        self._w.writerow([d.get(k, "") for k in self.fieldnames])
    def writerows(self, rows):
        for d in rows:
            self.writerow(d)
)NSLIB"
        },
        {"dataclasses",
         R"NSLIB(# @dataclass itself is expanded by the parser; this module has the helpers around it.
def dataclass(cls=None, **kw):
    if cls is None:
        return lambda c: c
    return cls

def field(default=None, default_factory=None, **kw):
    return {"__dcfield__": True, "default": default, "default_factory": default_factory}

def asdict(obj):
    out = {}
    for k in vars(obj):
        v = getattr(obj, k)
        out[k] = asdict(v) if hasattr(v, "__class__") and hasattr(v, "_dc_key") is False and _is_dc(v) else v
    return out

def _is_dc(v):
    return hasattr(v, "__class__") and not isinstance(v, (list, dict, str, int, float, bool)) and v is not None

def astuple(obj):
    return tuple([getattr(obj, k) for k in vars(obj)])

def fields(obj):
    return list(vars(obj).keys())

def replace(obj, **changes):
    d = vars(obj)
    d.update(changes)
    return type(obj)(**d)

def is_dataclass(obj):
    return hasattr(obj, "__class__")
)NSLIB"
        },
        {"enum",
         R"NSLIB(# class Color(Enum): RED = 1  -- members are objects with .name and .value (made by the parser's _enum_init)
class Enum:
    def __str__(self):
        return type(self).__name__ + "." + self.name
    def __repr__(self):
        return "<" + type(self).__name__ + "." + self.name + ": " + repr(self.value) + ">"
    def __hash__(self):
        return hash(self.name)

class IntEnum(Enum):
    pass

class StrEnum(Enum):
    pass

class Flag(Enum):
    pass

class IntFlag(Flag):
    pass

def auto():
    return {"__auto__": True}

def unique(cls):
    return cls
)NSLIB"
        },
        {"fnmatch",
         R"NSLIB(import re

def translate(pat):
    i = 0
    n = len(pat)
    res = ""
    while i < n:
        c = pat[i]
        i += 1
        if c == "*":
            res += ".*"
        elif c == "?":
            res += "."
        elif c == "[":
            j = i
            if j < n and pat[j] == "!":
                j += 1
            if j < n and pat[j] == "]":
                j += 1
            while j < n and pat[j] != "]":
                j += 1
            if j >= n:
                res += "\\["
            else:
                stuff = pat[i:j]
                i = j + 1
                if stuff[0] == "!":
                    stuff = "^" + stuff[1:]
                res += "[" + stuff + "]"
        else:
            if c in ".^$+{}()|\\":
                res += "\\" + c
            else:
                res += c
    return "^" + res + "$"

def fnmatch(name, pat):
    return re.match(translate(pat), name) is not None

fnmatchcase = fnmatch

def filter(names, pat):
    rx = translate(pat)
    return [n for n in names if re.match(rx, n) is not None]
)NSLIB"
        },
        {"fractions",
         R"NSLIB(import math

class Fraction:
    def __init__(self, numerator=0, denominator=1):
        if isinstance(numerator, str):
            if "/" in numerator:
                a, _, b = numerator.partition("/")
                numerator = int(a)
                denominator = int(b)
            elif "." in numerator:
                whole, _, frac = numerator.partition(".")
                denominator = 10 ** len(frac)
                numerator = int(whole + frac)
            else:
                numerator = int(numerator)
        elif isinstance(numerator, float) and numerator != int(numerator):
            s = repr(numerator)
            whole, _, frac = s.partition(".")
            denominator = 10 ** len(frac)
            numerator = int(whole + frac)
        if denominator == 0:
            raise ZeroDivisionError("Fraction(" + str(numerator) + ", 0)")
        if denominator < 0:
            numerator = -numerator
            denominator = -denominator
        g = math.gcd(abs(int(numerator)), int(denominator))
        if g == 0:
            g = 1
        self.numerator = int(numerator) // g
        self.denominator = int(denominator) // g
    def _f(self, o):
        return o if isinstance(o, Fraction) else Fraction(o)
    def __add__(self, o):
        o = self._f(o)
        return Fraction(self.numerator * o.denominator + o.numerator * self.denominator, self.denominator * o.denominator)
    def __radd__(self, o):
        return self.__add__(o)
    def __sub__(self, o):
        o = self._f(o)
        return Fraction(self.numerator * o.denominator - o.numerator * self.denominator, self.denominator * o.denominator)
    def __rsub__(self, o):
        return self._f(o).__sub__(self)
    def __mul__(self, o):
        o = self._f(o)
        return Fraction(self.numerator * o.numerator, self.denominator * o.denominator)
    def __rmul__(self, o):
        return self.__mul__(o)
    def __truediv__(self, o):
        o = self._f(o)
        return Fraction(self.numerator * o.denominator, self.denominator * o.numerator)
    def __rtruediv__(self, o):
        return self._f(o).__truediv__(self)
    def __neg__(self):
        return Fraction(-self.numerator, self.denominator)
    def __eq__(self, o):
        if isinstance(o, (int, float, Fraction)):
            o = self._f(o)
            return self.numerator == o.numerator and self.denominator == o.denominator
        return False
    def __lt__(self, o):
        o = self._f(o)
        return self.numerator * o.denominator < o.numerator * self.denominator
    def __le__(self, o):
        o = self._f(o)
        return self.numerator * o.denominator <= o.numerator * self.denominator
    def __gt__(self, o):
        o = self._f(o)
        return self.numerator * o.denominator > o.numerator * self.denominator
    def __ge__(self, o):
        o = self._f(o)
        return self.numerator * o.denominator >= o.numerator * self.denominator
    def __hash__(self):
        return hash(self.numerator / self.denominator)
    def __float__(self):
        return self.numerator / self.denominator
    def __str__(self):
        if self.denominator == 1:
            return str(self.numerator)
        return str(self.numerator) + "/" + str(self.denominator)
    def __repr__(self):
        return "Fraction(" + str(self.numerator) + ", " + str(self.denominator) + ")"
    def limit_denominator(self, max_denominator=1000000):
        return self
)NSLIB"
        },
        {"functools",
         R"NSLIB(def reduce(function, iterable, initial=None):
    it = list(iterable)
    if initial is None:
        if len(it) == 0:
            raise TypeError("reduce() of empty iterable with no initial value")
        acc = it[0]
        it = it[1:]
    else:
        acc = initial
    for x in it:
        acc = function(acc, x)
    return acc

def partial(fn, *pargs, **pkw):
    def call(*args, **kw):
        merged = dict(pkw)
        merged.update(kw)
        return fn(*(list(pargs) + list(args)), **merged)
    return call

def wraps(wrapped):
    def deco(f):
        return f
    return deco

def lru_cache(maxsize=128, typed=False):
    def deco(fn):
        cache = {}
        def wrapper(*args):
            key = str(args)
            if key in cache:
                return cache[key]
            r = fn(*args)
            cache[key] = r
            return r
        return wrapper
    if callable(maxsize):
        f = maxsize
        maxsize = 128
        return deco(f)
    return deco

def cache(fn):
    return lru_cache()(fn)

def cmp_to_key(mycmp):
    class K:
        def __init__(self, obj):
            self.obj = obj
        def __lt__(self, other):
            return mycmp(self.obj, other.obj) < 0
        def __gt__(self, other):
            return mycmp(self.obj, other.obj) > 0
        def __eq__(self, other):
            return mycmp(self.obj, other.obj) == 0
    return K

def total_ordering(cls):
    return cls

def singledispatch(fn):
    return fn
)NSLIB"
        },
        {"glob",
         R"NSLIB(import os
import fnmatch

def _has_magic(s):
    return "*" in s or "?" in s or "[" in s

def _walk(top):
    out = []
    try:
        names = os.listdir(top)
    except Exception:
        return out
    for n in names:
        p = top + "/" + n if top != "" else n
        out.append(p)
        if os.path.isdir(p):
            out.extend(_walk(p))
    return out

def glob(pattern, recursive=False):
    if not _has_magic(pattern):
        return [pattern] if os.path.exists(pattern) else []
    parts = pattern.split("/")
    results = [""] if not pattern.startswith("/") else ["/"]
    if pattern.startswith("/"):
        parts = parts[1:]
    for idx in range(len(parts)):
        part = parts[idx]
        last = idx == len(parts) - 1
        nxt = []
        for base in results:
            if part == "**" and recursive:
                nxt.append(base)
                top = base if base != "" else "."
                for p in _walk(top):
                    if os.path.isdir(p):
                        nxt.append(p[2:] if p.startswith("./") else p)
            elif _has_magic(part):
                d = base if base != "" else "."
                try:
                    names = os.listdir(d)
                except Exception:
                    names = []
                for n in names:
                    if n.startswith(".") and not part.startswith("."):
                        continue
                    if fnmatch.fnmatch(n, part):
                        p = n if base == "" else (base + n if base.endswith("/") else base + "/" + n)
                        if last or os.path.isdir(p):
                            nxt.append(p)
            else:
                p = part if base == "" else (base + part if base.endswith("/") else base + "/" + part)
                if os.path.exists(p):
                    nxt.append(p)
        results = nxt
    return sorted(set(results))

def iglob(pattern, recursive=False):
    for p in glob(pattern, recursive):
        yield p

def escape(pathname):
    out = ""
    for c in pathname:
        if c in "*?[":
            out += "[" + c + "]"
        else:
            out += c
    return out
)NSLIB"
        },
        {"heapq",
         R"NSLIB(# heapq: binary min-heap on a plain list.
def _siftdown(heap, start, pos):
    newitem = heap[pos]
    while pos > start:
        parent = (pos - 1) >> 1
        p = heap[parent]
        if newitem < p:
            heap[pos] = p
            pos = parent
            continue
        break
    heap[pos] = newitem

def _siftup(heap, pos):
    end = len(heap)
    start = pos
    newitem = heap[pos]
    child = 2 * pos + 1
    while child < end:
        right = child + 1
        if right < end and not (heap[child] < heap[right]):
            child = right
        heap[pos] = heap[child]
        pos = child
        child = 2 * pos + 1
    heap[pos] = newitem
    _siftdown(heap, start, pos)

def heappush(heap, item):
    heap.append(item)
    _siftdown(heap, 0, len(heap) - 1)

def heappop(heap):
    last = heap.pop()
    if heap:
        ret = heap[0]
        heap[0] = last
        _siftup(heap, 0)
        return ret
    return last

def heapreplace(heap, item):
    ret = heap[0]
    heap[0] = item
    _siftup(heap, 0)
    return ret

def heappushpop(heap, item):
    if heap and heap[0] < item:
        item, heap[0] = heap[0], item
        _siftup(heap, 0)
    return item

def heapify(heap):
    n = len(heap)
    for i in reversed(range(n // 2)):
        _siftup(heap, i)

def nlargest(n, iterable, key=None):
    return sorted(iterable, key=key, reverse=True)[:n]

def nsmallest(n, iterable, key=None):
    return sorted(iterable, key=key)[:n]

def merge(*iterables):
    items = []
    for it in iterables:
        for x in it:
            items.append(x)
    for x in sorted(items):
        yield x
)NSLIB"
        },
        {"io",
         R"NSLIB(class StringIO:
    def __init__(self, initial_value=""):
        self._buf = initial_value
        self._pos = 0
        self.closed = False
    def write(self, s):
        self._buf = self._buf + s
        return len(s)
    def read(self, n=None):
        rest = self._buf[self._pos:]
        if n is not None:
            rest = rest[:n]
        self._pos = self._pos + len(rest)
        return rest
    def readline(self):
        rest = self._buf[self._pos:]
        i = rest.find("\n")
        line = rest if i < 0 else rest[:i + 1]
        self._pos = self._pos + len(line)
        return line
    def readlines(self):
        out = []
        while True:
            l = self.readline()
            if l == "":
                break
            out.append(l)
        return out
    def getvalue(self):
        return self._buf
    def seek(self, pos, whence=0):
        self._pos = pos
        return pos
    def tell(self):
        return self._pos
    def truncate(self, size=None):
        self._buf = self._buf[:size if size is not None else self._pos]
    def close(self):
        self.closed = True
    def flush(self):
        pass
    def __iter__(self):
        return iter(self.readlines())
    def __enter__(self):
        return self
    def __exit__(self, a, b, c):
        self.closed = True
        return False

BytesIO = StringIO
TextIOWrapper = StringIO
)NSLIB"
        },
        {"itertools",
         R"NSLIB(# itertools: lazy iterators built from generators.
def count(start=0, step=1):
    n = start
    while True:
        yield n
        n += step

def cycle(iterable):
    saved = []
    for x in iterable:
        yield x
        saved.append(x)
    while saved:
        for x in saved:
            yield x

def repeat(obj, times=None):
    if times is None:
        while True:
            yield obj
    else:
        for _ in range(times):
            yield obj

def chain(*iterables):
    for it in iterables:
        for x in it:
            yield x

def chain_from_iterable(iterables):
    for it in iterables:
        for x in it:
            yield x

def islice(iterable, *args):
    start = 0
    step = 1
    if len(args) == 1:
        stop = args[0]
    elif len(args) == 2:
        start = args[0]
        stop = args[1]
    else:
        start = args[0]
        stop = args[1]
        step = args[2]
    if start is None:
        start = 0
    if step is None:
        step = 1
    if stop is not None and start >= stop:
        return
    i = 0
    nxt = start
    for x in iterable:
        if i == nxt:
            yield x
            nxt += step
            if stop is not None and nxt >= stop:
                return
        i += 1

def takewhile(pred, iterable):
    for x in iterable:
        if not pred(x):
            return
        yield x

def dropwhile(pred, iterable):
    dropping = True
    for x in iterable:
        if dropping and pred(x):
            continue
        dropping = False
        yield x

def filterfalse(pred, iterable):
    for x in iterable:
        if pred is None:
            if not x:
                yield x
        elif not pred(x):
            yield x

def starmap(func, iterable):
    for args in iterable:
        yield func(*args)

def compress(data, selectors):
    for d, s in zip(data, selectors):
        if s:
            yield d

def accumulate(iterable, func=None, initial=None):
    total = initial
    started = initial is not None
    if started:
        yield total
    for x in iterable:
        if not started:
            total = x
            started = True
        elif func is None:
            total = total + x
        else:
            total = func(total, x)
        yield total

def pairwise(iterable):
    prev = None
    first = True
    for x in iterable:
        if first:
            first = False
        else:
            yield (prev, x)
        prev = x

def batched(iterable, n):
    batch = []
    for x in iterable:
        batch.append(x)
        if len(batch) == n:
            yield tuple(batch)
            batch = []
    if batch:
        yield tuple(batch)

def groupby(iterable, key=None):
    started = False
    cur = None
    group = []
    for x in iterable:
        k = x if key is None else key(x)
        if started and k == cur:
            group.append(x)
        else:
            if started:
                yield (cur, group)
            cur = k
            group = [x]
            started = True
    if started:
        yield (cur, group)

def zip_longest(*iterables, **kw):
    fill = kw.get("fillvalue", None)
    lists = [list(it) for it in iterables]
    n = 0
    for l in lists:
        if len(l) > n:
            n = len(l)
    for i in range(n):
        yield tuple([l[i] if i < len(l) else fill for l in lists])

def tee(iterable, n=2):
    items = list(iterable)
    return tuple([iter(items) for _ in range(n)])

def product(*iterables, **kw):
    reps = kw.get("repeat", 1)
    pools = [list(p) for p in iterables] * reps
    result = [[]]
    for pool in pools:
        result = [x + [y] for x in result for y in pool]
    for prod in result:
        yield tuple(prod)

def permutations(iterable, r=None):
    pool = list(iterable)
    n = len(pool)
    if r is None:
        r = n
    def rec(prefix, remaining):
        if len(prefix) == r:
            yield tuple(prefix)
            return
        for i in range(len(remaining)):
            yield from rec(prefix + [remaining[i]], remaining[:i] + remaining[i + 1:])
    if r <= n:
        yield from rec([], pool)

def combinations(iterable, r):
    pool = list(iterable)
    n = len(pool)
    def rec(start, prefix):
        if len(prefix) == r:
            yield tuple(prefix)
            return
        for i in range(start, n):
            yield from rec(i + 1, prefix + [pool[i]])
    yield from rec(0, [])

def combinations_with_replacement(iterable, r):
    pool = list(iterable)
    n = len(pool)
    def rec(start, prefix):
        if len(prefix) == r:
            yield tuple(prefix)
            return
        for i in range(start, n):
            yield from rec(i, prefix + [pool[i]])
    yield from rec(0, [])
)NSLIB"
        },
        {"logging",
         R"NSLIB(import sys
import time

CRITICAL = 50
FATAL = 50
ERROR = 40
WARNING = 30
WARN = 30
INFO = 20
DEBUG = 10
NOTSET = 0

_names = {50: "CRITICAL", 40: "ERROR", 30: "WARNING", 20: "INFO", 10: "DEBUG", 0: "NOTSET"}
_root = {"level": 30, "format": "%(levelname)s:%(name)s:%(message)s", "datefmt": None, "file": None, "stream": None}
_loggers = {}

def getLevelName(level):
    return _names.get(level, "Level " + str(level))

def _render(fmt, name, level, msg, datefmt):
    ts = time.strftime(datefmt or "%Y-%m-%d %H:%M:%S")
    out = fmt
    out = out.replace("%(asctime)s", ts)
    out = out.replace("%(levelname)s", getLevelName(level))
    out = out.replace("%(name)s", name)
    out = out.replace("%(message)s", msg)
    out = out.replace("%(levelno)s", str(level))
    return out

class Handler:
    def __init__(self, level=0):
        self.level = level
        self.formatter = None
    def setLevel(self, level):
        self.level = level
    def setFormatter(self, fmt):
        self.formatter = fmt
    def emit(self, line):
        pass

class StreamHandler(Handler):
    def __init__(self, stream=None):
        Handler.__init__(self)
        self.stream = stream
    def emit(self, line):
        if self.stream is None or self.stream is sys.stderr:
            sys.stderr.write(line + "\n")
        else:
            self.stream.write(line + "\n")

class FileHandler(Handler):
    def __init__(self, filename, mode="a"):
        Handler.__init__(self)
        self.filename = filename
    def emit(self, line):
        with open(self.filename, "a") as f:
            f.write(line + "\n")

class Formatter:
    def __init__(self, fmt=None, datefmt=None):
        self.fmt = fmt
        self.datefmt = datefmt

class Logger:
    def __init__(self, name):
        self.name = name
        self.level = 0
        self.handlers = []
        self.propagate = True
    def setLevel(self, level):
        self.level = level
    def addHandler(self, h):
        self.handlers.append(h)
    def removeHandler(self, h):
        self.handlers.remove(h)
    def getEffectiveLevel(self):
        return self.level if self.level != 0 else _root["level"]
    def isEnabledFor(self, level):
        return level >= self.getEffectiveLevel()
    def log(self, level, msg, *args):
        if not self.isEnabledFor(level):
            return
        text = str(msg)
        if len(args) > 0:
            text = text % args
        if len(self.handlers) > 0:
            for h in self.handlers:
                if level >= h.level:
                    f = h.formatter
                    fmt = f.fmt if f is not None and f.fmt is not None else "%(message)s"
                    h.emit(_render(fmt, self.name, level, text, f.datefmt if f is not None else None))
            return
        line = _render(_root["format"], self.name, level, text, _root["datefmt"])
        if _root["file"] is not None:
            with open(_root["file"], "a") as fh:
                fh.write(line + "\n")
        else:
            sys.stderr.write(line + "\n")
    def debug(self, msg, *args):
        self.log(10, msg, *args)
    def info(self, msg, *args):
        self.log(20, msg, *args)
    def warning(self, msg, *args):
        self.log(30, msg, *args)
    def warn(self, msg, *args):
        self.log(30, msg, *args)
    def error(self, msg, *args):
        self.log(40, msg, *args)
    def critical(self, msg, *args):
        self.log(50, msg, *args)
    def exception(self, msg, *args):
        self.log(40, msg, *args)

def getLogger(name="root"):
    if name not in _loggers:
        _loggers[name] = Logger(name)
    return _loggers[name]

def basicConfig(**kw):
    if "level" in kw:
        _root["level"] = kw["level"]
    if "format" in kw:
        _root["format"] = kw["format"]
    if "datefmt" in kw:
        _root["datefmt"] = kw["datefmt"]
    if "filename" in kw:
        _root["file"] = kw["filename"]

def debug(msg, *args):
    getLogger("root").log(10, msg, *args)
def info(msg, *args):
    getLogger("root").log(20, msg, *args)
def warning(msg, *args):
    getLogger("root").log(30, msg, *args)
warn = warning
def error(msg, *args):
    getLogger("root").log(40, msg, *args)
def critical(msg, *args):
    getLogger("root").log(50, msg, *args)
def exception(msg, *args):
    getLogger("root").log(40, msg, *args)
def log(level, msg, *args):
    getLogger("root").log(level, msg, *args)
def disable(level=50):
    _root["level"] = level + 1
)NSLIB"
        },
        {"operator",
         R"NSLIB(def add(a, b):
    return a + b
def sub(a, b):
    return a - b
def mul(a, b):
    return a * b
def truediv(a, b):
    return a / b
def floordiv(a, b):
    return a // b
def mod(a, b):
    return a % b
def pow(a, b):
    return a ** b
def neg(a):
    return -a
def eq(a, b):
    return a == b
def ne(a, b):
    return a != b
def lt(a, b):
    return a < b
def le(a, b):
    return a <= b
def gt(a, b):
    return a > b
def ge(a, b):
    return a >= b
def not_(a):
    return not a
def and_(a, b):
    return a & b
def or_(a, b):
    return a | b
def xor(a, b):
    return a ^ b
def contains(a, b):
    return b in a
def getitem(a, b):
    return a[b]
def concat(a, b):
    return a + b
def itemgetter(*items):
    if len(items) == 1:
        item = items[0]
        return lambda obj: obj[item]
    return lambda obj: tuple([obj[i] for i in items])
def attrgetter(*names):
    def get(obj, name):
        for part in name.split("."):
            obj = getattr(obj, part)
        return obj
    if len(names) == 1:
        n = names[0]
        return lambda obj: get(obj, n)
    return lambda obj: tuple([get(obj, n) for n in names])
def methodcaller(name, *args, **kw):
    return lambda obj: getattr(obj, name)(*args, **kw)
)NSLIB"
        },
        {"os",
         R"NSLIB(getcwd = _os_getcwd
chdir = _os_chdir
listdir = _os_listdir
mkdir = _os_mkdir
makedirs = _os_makedirs
remove = _os_remove
unlink = _os_remove
rmdir = _os_rmdir
rename = _os_rename
replace = _os_rename
system = _os_system
getpid = _os_getpid
cpu_count = _os_cpu_count
environ = _os_environ()
sep = "/"
pathsep = ":"
name = "posix"
linesep = "\n"
curdir = "."
pardir = ".."

def getenv(key, default=None):
    return _os_getenv(key, default)

def putenv(key, value):
    environ[key] = value

def getmtime(p):
    return _os_mtime(p)

def _isabs(p):
    return p.startswith("/")

def _normpath(p):
    if p == "":
        return "."
    absolute = p.startswith("/")
    segs = []
    for s in p.split("/"):
        if s == "" or s == ".":
            continue
        if s == "..":
            if len(segs) > 0 and segs[-1] != "..":
                segs.pop()
            elif not absolute:
                segs.append("..")
        else:
            segs.append(s)
    out = "/".join(segs)
    if absolute:
        return "/" + out
    return out if out != "" else "."

def _split(p):
    i = p.rfind("/")
    if i < 0:
        return ("", p)
    head = p[:i + 1]
    if head != "/" * len(head):
        head = head.rstrip("/")
    return (head, p[i + 1:])

def _relpath(p, start="."):
    a = _normpath(_os_abspath(p)).split("/")
    b = _normpath(_os_abspath(start)).split("/")
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    parts = [".."] * (len(b) - i) + a[i:]
    return "/".join(parts) if len(parts) > 0 else "."

def _splitext_all(p):
    return _os_splitext(p)

path = {"join": _os_join, "exists": _os_exists, "isfile": _os_isfile, "isdir": _os_isdir,
        "getsize": _os_getsize, "abspath": _os_abspath, "basename": _os_basename,
        "dirname": _os_dirname, "splitext": _os_splitext, "expanduser": _os_expanduser, "sep": "/",
        "getmtime": _os_mtime, "isabs": _isabs, "normpath": _normpath, "split": _split,
        "realpath": _os_abspath, "relpath": _relpath, "lexists": _os_exists,
        "islink": lambda p: False, "expandvars": lambda p: p}

class DirEntry:
    def __init__(self, dirpath, n):
        self.name = n
        self.path = dirpath + "/" + n if dirpath != "" else n
    def is_dir(self):
        return _os_isdir(self.path)
    def is_file(self):
        return _os_isfile(self.path)
    def is_symlink(self):
        return False
    def stat(self):
        return stat(self.path)

def scandir(p="."):
    return [DirEntry(p, n) for n in _os_listdir(p)]

def walk(top, topdown=True):
    dirs = []
    files = []
    for n in _os_listdir(top):
        if _os_isdir(top + "/" + n):
            dirs.append(n)
        else:
            files.append(n)
    if topdown:
        yield (top, dirs, files)
    for d in dirs:
        yield from walk(top + "/" + d, topdown)
    if not topdown:
        yield (top, dirs, files)

class stat_result:
    def __init__(self, p):
        self.st_size = _os_getsize(p) if _os_isfile(p) else 0
        self.st_mtime = _os_mtime(p)
        self.st_mode = 0o40755 if _os_isdir(p) else 0o100644

def stat(p):
    return stat_result(p)

def chmod(p, mode):
    _os_system("chmod " + oct(mode)[2:] + " '" + p + "'")

def urandom(n):
    import random
    return "".join([chr(random.randint(0, 255)) for i in range(n)])

def get_terminal_size():
    return (80, 24)

def kill(pid, sig):
    _os_system("kill -" + str(sig) + " " + str(pid))

def isatty(fd):
    return False
)NSLIB"
        },
        {"pathlib",
         R"NSLIB(import os
import glob as _glob
import fnmatch
import shutil

class Path:
    def __init__(self, *parts):
        p = ""
        for x in parts:
            s = str(x)
            if s.startswith("/"):
                p = s
            elif p == "":
                p = s
            else:
                p = p + ("" if p.endswith("/") else "/") + s
        if p == "":
            p = "."
        while len(p) > 1 and p.endswith("/"):
            p = p[:-1]
        self._p = p
    def __str__(self):
        return self._p
    def __repr__(self):
        return "PosixPath('" + self._p + "')"
    def __truediv__(self, other):
        return Path(self._p, str(other))
    def __eq__(self, other):
        return str(other) == self._p
    def __lt__(self, other):
        return self._p < str(other)
    def joinpath(self, *others):
        return Path(self._p, *others)
    @property
    def name(self):
        return self._p.split("/")[-1] if self._p != "/" else ""
    @property
    def suffix(self):
        n = self.name
        i = n.rfind(".")
        return n[i:] if i > 0 else ""
    @property
    def suffixes(self):
        n = self.name
        parts = n.split(".")
        return ["." + s for s in parts[1:]] if n.startswith(".") is False else []
    @property
    def stem(self):
        n = self.name
        i = n.rfind(".")
        return n[:i] if i > 0 else n
    @property
    def parent(self):
        i = self._p.rfind("/")
        if i < 0:
            return Path(".")
        if i == 0:
            return Path("/")
        return Path(self._p[:i])
    @property
    def parents(self):
        out = []
        p = self.parent
        while True:
            out.append(p)
            if str(p) in (".", "/"):
                break
            p = p.parent
        return out
    @property
    def parts(self):
        segs = [s for s in self._p.split("/") if s != ""]
        if self._p.startswith("/"):
            return tuple(["/"] + segs)
        return tuple(segs)
    @property
    def anchor(self):
        return "/" if self._p.startswith("/") else ""
    def is_absolute(self):
        return self._p.startswith("/")
    def exists(self):
        return os.path.exists(self._p)
    def is_file(self):
        return os.path.isfile(self._p)
    def is_dir(self):
        return os.path.isdir(self._p)
    def read_text(self, encoding=None):
        with open(self._p) as f:
            return f.read()
    def write_text(self, data, encoding=None):
        with open(self._p, "w") as f:
            f.write(data)
        return len(data)
    def read_bytes(self):
        return self.read_text()
    def write_bytes(self, data):
        return self.write_text(data)
    def open(self, mode="r", **kw):
        return open(self._p, mode)
    def mkdir(self, mode=0o777, parents=False, exist_ok=False):
        if os.path.exists(self._p):
            if exist_ok:
                return None
            raise FileExistsError(self._p)
        if parents:
            os.makedirs(self._p)
        else:
            os.mkdir(self._p)
    def unlink(self, missing_ok=False):
        if not os.path.exists(self._p) and missing_ok:
            return None
        os.remove(self._p)
    def rmdir(self):
        os.rmdir(self._p)
    def rename(self, target):
        os.rename(self._p, str(target))
        return Path(target)
    def replace(self, target):
        return self.rename(target)
    def touch(self, exist_ok=True):
        if not os.path.exists(self._p):
            with open(self._p, "w") as f:
                f.write("")
    def iterdir(self):
        for n in os.listdir(self._p):
            yield Path(self._p, n)
    def glob(self, pattern):
        for p in _glob.glob(self._p + "/" + pattern, recursive=True):
            yield Path(p)
    def rglob(self, pattern):
        for p in _glob.glob(self._p + "/**/" + pattern, recursive=True):
            yield Path(p)
    def resolve(self):
        return Path(os.path.abspath(self._p))
    def absolute(self):
        return self.resolve()
    def expanduser(self):
        return Path(os.path.expanduser(self._p))
    def with_suffix(self, suffix):
        return self.parent / (self.stem + suffix)
    def with_name(self, name):
        return self.parent / name
    def with_stem(self, stem):
        return self.parent / (stem + self.suffix)
    def relative_to(self, other):
        o = str(other)
        if not self._p.startswith(o):
            raise ValueError(self._p + " is not in the subpath of " + o)
        return Path(self._p[len(o):].lstrip("/"))
    def stat(self):
        return {"st_size": os.path.getsize(self._p), "st_mtime": os.path.getmtime(self._p)}
    def samefile(self, other):
        return os.path.abspath(self._p) == os.path.abspath(str(other))
    @staticmethod
    def cwd():
        return Path(os.getcwd())
    @staticmethod
    def home():
        return Path(os.path.expanduser("~"))

PurePath = Path
PosixPath = Path
PurePosixPath = Path
)NSLIB"
        },
        {"platform",
         R"NSLIB(import sys

def system():
    p = sys.platform
    return "Linux" if p.startswith("linux") else ("Darwin" if p == "darwin" else p)

def machine():
    return "x86_64"

def python_version():
    return "3.11.0"

def python_implementation():
    return "Nusantara"

def node():
    return "localhost"

def platform():
    return system()

def uname():
    return {"system": system(), "node": node(), "machine": machine()}
)NSLIB"
        },
        {"pprint",
         R"NSLIB(import json

def pformat(obj, indent=1, width=80, **kw):
    return json.dumps(obj, indent=max(indent, 2), sort_keys=False)

def pprint(obj, *args, **kw):
    print(pformat(obj))

pp = pprint
)NSLIB"
        },
        {"queue",
         R"NSLIB(class Empty(Exception):
    pass

class Full(Exception):
    pass

class Queue:
    def __init__(self, maxsize=0):
        self._items = []
        self.maxsize = maxsize
        self._unfinished = 0
    def put(self, item, block=True, timeout=None):
        if self.maxsize > 0 and len(self._items) >= self.maxsize:
            raise Full("queue is full")
        self._items.append(item)
        self._unfinished += 1
    def put_nowait(self, item):
        self.put(item)
    def get(self, block=True, timeout=None):
        waited = 0.0
        while len(self._items) == 0:
            if not block or (timeout is not None and waited >= timeout):
                raise Empty("queue is empty")
            tidur(1)
            waited += 0.001
        return self._items.pop(0)
    def get_nowait(self):
        return self.get(False)
    def qsize(self):
        return len(self._items)
    def empty(self):
        return len(self._items) == 0
    def full(self):
        return self.maxsize > 0 and len(self._items) >= self.maxsize
    def task_done(self):
        self._unfinished -= 1
    def join(self):
        while self._unfinished > 0:
            tidur(1)

class LifoQueue(Queue):
    def get(self, block=True, timeout=None):
        waited = 0.0
        while len(self._items) == 0:
            if not block or (timeout is not None and waited >= timeout):
                raise Empty("queue is empty")
            tidur(1)
            waited += 0.001
        return self._items.pop()

class PriorityQueue(Queue):
    def put(self, item, block=True, timeout=None):
        Queue.put(self, item)
        self._items.sort()
)NSLIB"
        },
        {"secrets",
         R"NSLIB(import random

def token_hex(nbytes=32):
    digits = "0123456789abcdef"
    out = ""
    for i in range(nbytes * 2):
        out += digits[random.randint(0, 15)]
    return out

def token_urlsafe(nbytes=32):
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
    out = ""
    for i in range(nbytes * 4 // 3 + 1):
        out += chars[random.randint(0, 63)]
    return out

def randbelow(n):
    return random.randint(0, n - 1)

def choice(seq):
    return random.choice(seq)

def compare_digest(a, b):
    return a == b
)NSLIB"
        },
        {"shutil",
         R"NSLIB(import os

def copyfile(src, dst):
    _os_copyfile(src, dst)
    return dst

def copy(src, dst):
    if os.path.isdir(dst):
        dst = dst + "/" + os.path.basename(src)
    _os_copyfile(src, dst)
    return dst

copy2 = copy

def copytree(src, dst, dirs_exist_ok=False):
    os.makedirs(dst)
    for n in os.listdir(src):
        s = src + "/" + n
        d = dst + "/" + n
        if os.path.isdir(s):
            copytree(s, d)
        else:
            _os_copyfile(s, d)
    return dst

def move(src, dst):
    if os.path.isdir(dst):
        dst = dst + "/" + os.path.basename(src)
    os.rename(src, dst)
    return dst

def rmtree(path, ignore_errors=False):
    _os_rmtree(path)

def which(cmd):
    if "/" in cmd:
        return cmd if os.path.exists(cmd) else None
    for d in (os.getenv("PATH") or "").split(":"):
        p = d + "/" + cmd
        if os.path.isfile(p):
            return p
    return None

def disk_usage(path):
    return {"total": 0, "used": 0, "free": 0}

def get_terminal_size():
    return (80, 24)
)NSLIB"
        },
        {"statistics",
         R"NSLIB(import math

def mean(data):
    d = list(data)
    if len(d) == 0:
        raise ValueError("mean requires at least one data point")
    return sum(d) / len(d)

fmean = mean

def median(data):
    d = sorted(data)
    n = len(d)
    if n == 0:
        raise ValueError("no median for empty data")
    if n % 2 == 1:
        return d[n // 2]
    return (d[n // 2 - 1] + d[n // 2]) / 2

def median_low(data):
    d = sorted(data)
    n = len(d)
    return d[n // 2] if n % 2 == 1 else d[n // 2 - 1]

def median_high(data):
    d = sorted(data)
    return d[len(d) // 2]

def mode(data):
    counts = {}
    best = None
    bestn = 0
    for x in data:
        counts[x] = counts.get(x, 0) + 1
        if counts[x] > bestn:
            bestn = counts[x]
            best = x
    if best is None:
        raise ValueError("no mode for empty data")
    return best

def multimode(data):
    counts = {}
    for x in data:
        counts[x] = counts.get(x, 0) + 1
    if not counts:
        return []
    top = max(counts.values())
    return [k for k in counts if counts[k] == top]

def pvariance(data, mu=None):
    d = list(data)
    if mu is None:
        mu = sum(d) / len(d)
    return sum([(x - mu) ** 2 for x in d]) / len(d)

def variance(data, xbar=None):
    d = list(data)
    if len(d) < 2:
        raise ValueError("variance requires at least two data points")
    if xbar is None:
        xbar = sum(d) / len(d)
    return sum([(x - xbar) ** 2 for x in d]) / (len(d) - 1)

def pstdev(data, mu=None):
    return math.sqrt(pvariance(data, mu))

def stdev(data, xbar=None):
    return math.sqrt(variance(data, xbar))
)NSLIB"
        },
        {"tempfile",
         R"NSLIB(import os
import random
import shutil

def gettempdir():
    return os.getenv("TMPDIR") or "/tmp"

def _name(prefix, suffix):
    digits = "abcdefghijklmnopqrstuvwxyz0123456789_"
    s = ""
    for i in range(8):
        s += digits[random.randint(0, 36)]
    return gettempdir() + "/" + prefix + s + suffix

def mkdtemp(suffix="", prefix="tmp", dir=None):
    p = _name(prefix, suffix)
    os.makedirs(p)
    return p

def mktemp(suffix="", prefix="tmp", dir=None):
    return _name(prefix, suffix)

def mkstemp(suffix="", prefix="tmp", dir=None):
    p = _name(prefix, suffix)
    with open(p, "w") as f:
        f.write("")
    return (0, p)

class TemporaryDirectory:
    def __init__(self, suffix="", prefix="tmp", dir=None):
        self.name = mkdtemp(suffix, prefix)
    def cleanup(self):
        shutil.rmtree(self.name)
    def __enter__(self):
        return self.name
    def __exit__(self, a, b, c):
        self.cleanup()
        return False

class NamedTemporaryFile:
    def __init__(self, mode="w+", suffix="", prefix="tmp", delete=True):
        self.name = _name(prefix, suffix)
        self._delete = delete
        self._f = open(self.name, "w")
    def write(self, s):
        return self._f.write(s)
    def flush(self):
        self._f.flush()
    def close(self):
        self._f.close()
        if self._delete and os.path.exists(self.name):
            os.remove(self.name)
    def __enter__(self):
        return self
    def __exit__(self, a, b, c):
        self.close()
        return False
)NSLIB"
        },
        {"textwrap",
         R"NSLIB(def wrap(text, width=70, **kw):
    words = text.split()
    lines = []
    cur = ""
    for w in words:
        if cur == "":
            cur = w
        elif len(cur) + 1 + len(w) <= width:
            cur = cur + " " + w
        else:
            lines.append(cur)
            cur = w
    if cur != "":
        lines.append(cur)
    return lines

def fill(text, width=70, **kw):
    return "\n".join(wrap(text, width))

def dedent(text):
    lines = text.split("\n")
    margin = None
    for l in lines:
        if l.strip() == "":
            continue
        indent = len(l) - len(l.lstrip())
        if margin is None or indent < margin:
            margin = indent
    if not margin:
        return text
    return "\n".join([l[margin:] if l.strip() != "" else l.strip() for l in lines])

def indent(text, prefix, predicate=None):
    out = []
    for l in text.split("\n"):
        if (predicate is None and l.strip() != "") or (predicate is not None and predicate(l)):
            out.append(prefix + l)
        else:
            out.append(l)
    return "\n".join(out)

def shorten(text, width, placeholder=" [...]"):
    t = " ".join(text.split())
    if len(t) <= width:
        return t
    words = t.split()
    out = ""
    for w in words:
        cand = w if out == "" else out + " " + w
        if len(cand) + len(placeholder) > width:
            break
        out = cand
    return out + placeholder
)NSLIB"
        },
        {"threading",
         R"NSLIB(import time

_ident = [1]

class Thread:
    def __init__(self, group=None, target=None, name=None, args=(), kwargs=None, daemon=None):
        self._target = target
        self._args = args
        self._kwargs = kwargs if kwargs is not None else {}
        _ident[0] += 1
        self.name = name if name is not None else "Thread-" + str(_ident[0])
        self.ident = _ident[0]
        self.daemon = daemon
        self._done = kanal_baru(1)
        self._started = False
        self._alive = False
        self.result = None
        self.error = None
    def run(self):
        if self._target is not None:
            self.result = self._target(*self._args, **self._kwargs)
    def _main(self):
        try:
            self.run()
        except Exception as e:
            self.error = e
            print("Exception in thread " + self.name + ": " + str(e))
        self._alive = False
        kanal_tutup(self._done)
    def start(self):
        if self._started:
            raise RuntimeError("threads can only be started once")
        self._started = True
        self._alive = True
        me = self
        jalan(lambda: me._main())
    def join(self, timeout=None):
        if self._started:
            kanal_terima(self._done)
    def is_alive(self):
        return self._alive
    def isDaemon(self):
        return self.daemon

class Lock:
    def __init__(self):
        self._ch = kanal_baru(1)
    def acquire(self, blocking=True, timeout=-1):
        kanal_kirim(self._ch, 1)
        return True
    def release(self):
        kanal_terima(self._ch)
    def locked(self):
        return kanal_panjang(self._ch) > 0
    def __enter__(self):
        self.acquire()
        return self
    def __exit__(self, a, b, c):
        self.release()
        return False

RLock = Lock

class Event:
    def __init__(self):
        self._flag = False
    def set(self):
        self._flag = True
    def clear(self):
        self._flag = False
    def is_set(self):
        return self._flag
    def wait(self, timeout=None):
        waited = 0.0
        while not self._flag:
            time.sleep(0.001)
            waited += 0.001
            if timeout is not None and waited >= timeout:
                break
        return self._flag

class Semaphore:
    def __init__(self, value=1):
        self._ch = kanal_baru(value)
    def acquire(self, blocking=True):
        kanal_kirim(self._ch, 1)
        return True
    def release(self):
        kanal_terima(self._ch)
    def __enter__(self):
        self.acquire()
        return self
    def __exit__(self, a, b, c):
        self.release()
        return False

class Timer(Thread):
    def __init__(self, interval, function, args=(), kwargs=None):
        Thread.__init__(self, target=function, args=args, kwargs=kwargs)
        self.interval = interval
    def run(self):
        time.sleep(self.interval)
        self._target(*self._args, **self._kwargs)

def current_thread():
    t = Thread(name="MainThread")
    return t

def get_ident():
    return 1

def active_count():
    return 1

def cpu_count():
    return 1
)NSLIB"
        },
        {"typing",
         R"NSLIB(# Type hints are accepted and ignored: every name is a placeholder that subscripts to itself.
class _Any:
    def __init__(self, name):
        self._name = name
    def __getitem__(self, item):
        return self
    def __call__(self, *args, **kw):
        return self
    def __str__(self):
        return "typing." + self._name

Any = _Any("Any")
List = _Any("List")
Dict = _Any("Dict")
Set = _Any("Set")
FrozenSet = _Any("FrozenSet")
Tuple = _Any("Tuple")
Optional = _Any("Optional")
Union = _Any("Union")
Callable = _Any("Callable")
Iterable = _Any("Iterable")
Iterator = _Any("Iterator")
Generator = _Any("Generator")
Sequence = _Any("Sequence")
Mapping = _Any("Mapping")
MutableMapping = _Any("MutableMapping")
Type = _Any("Type")
ClassVar = _Any("ClassVar")
Final = _Any("Final")
Literal = _Any("Literal")
NoReturn = _Any("NoReturn")
Awaitable = _Any("Awaitable")
Protocol = _Any("Protocol")
Generic = _Any("Generic")
TypedDict = _Any("TypedDict")
NamedTuple = _Any("NamedTuple")
TYPE_CHECKING = False

def TypeVar(name, *args, **kw):
    return _Any(name)

def cast(tp, value):
    return value

def overload(fn):
    return fn

def final(fn):
    return fn

def no_type_check(fn):
    return fn
)NSLIB"
        },
        {"unittest",
         R"NSLIB(import sys

class AssertionFailed(Exception):
    pass

class TestCase:
    def assertEqual(self, a, b, msg=None):
        if not (a == b):
            raise AssertionError(msg or (repr(a) + " != " + repr(b)))
    def assertNotEqual(self, a, b, msg=None):
        if a == b:
            raise AssertionError(msg or (repr(a) + " == " + repr(b)))
    def assertTrue(self, x, msg=None):
        if not x:
            raise AssertionError(msg or (repr(x) + " is not true"))
    def assertFalse(self, x, msg=None):
        if x:
            raise AssertionError(msg or (repr(x) + " is not false"))
    def assertIs(self, a, b, msg=None):
        if a is not b:
            raise AssertionError(msg or (repr(a) + " is not " + repr(b)))
    def assertIsNone(self, x, msg=None):
        if x is not None:
            raise AssertionError(msg or (repr(x) + " is not None"))
    def assertIsNotNone(self, x, msg=None):
        if x is None:
            raise AssertionError(msg or "unexpectedly None")
    def assertIn(self, a, b, msg=None):
        if a not in b:
            raise AssertionError(msg or (repr(a) + " not found in " + repr(b)))
    def assertNotIn(self, a, b, msg=None):
        if a in b:
            raise AssertionError(msg or (repr(a) + " unexpectedly found in " + repr(b)))
    def assertGreater(self, a, b, msg=None):
        if not (a > b):
            raise AssertionError(msg or (repr(a) + " not greater than " + repr(b)))
    def assertGreaterEqual(self, a, b, msg=None):
        if not (a >= b):
            raise AssertionError(msg or (repr(a) + " not greater than or equal to " + repr(b)))
    def assertLess(self, a, b, msg=None):
        if not (a < b):
            raise AssertionError(msg or (repr(a) + " not less than " + repr(b)))
    def assertLessEqual(self, a, b, msg=None):
        if not (a <= b):
            raise AssertionError(msg or (repr(a) + " not less than or equal to " + repr(b)))
    def assertAlmostEqual(self, a, b, places=7, msg=None):
        if round(abs(a - b), places) != 0:
            raise AssertionError(msg or (repr(a) + " != " + repr(b) + " within " + str(places) + " places"))
    def assertIsInstance(self, obj, cls, msg=None):
        if not isinstance(obj, cls):
            raise AssertionError(msg or (repr(obj) + " is not an instance"))
    def assertListEqual(self, a, b, msg=None):
        self.assertEqual(a, b, msg)
    def assertDictEqual(self, a, b, msg=None):
        self.assertEqual(a, b, msg)
    def assertRaises(self, exc, fn=None, *args, **kw):
        if fn is None:
            return _RaisesCtx(exc)
        try:
            fn(*args, **kw)
        except Exception as e:
            if isinstance(e, exc):
                return None
            raise
        raise AssertionError(getattr(exc, "__name__", "exception") + " not raised")
    def fail(self, msg=None):
        raise AssertionError(msg or "failed")
    def setUp(self):
        pass
    def tearDown(self):
        pass

class _RaisesCtx:
    def __init__(self, exc):
        self.exc = exc
        self.exception = None
    def __enter__(self):
        return self
    def __exit__(self, t, value, tb):
        if value is None:
            raise AssertionError(getattr(self.exc, "__name__", "exception") + " not raised")
        if isinstance(value, self.exc):
            self.exception = value
            return True
        return False

def _run_class(cls):
    ok = 0
    failed = []
    names = [n for n in dir(cls()) if n.startswith("test")]
    for n in sorted(names):
        t = cls()
        try:
            t.setUp()
            getattr(t, n)()
            t.tearDown()
            ok += 1
            sys.stdout.write(".")
        except Exception as e:
            failed.append((cls.__name__ + "." + n, e))
            sys.stdout.write("F")
    return (ok, failed)

_classes = []

def register(cls):
    _classes.append(cls)
    return cls

def main(classes=None, **kw):
    total = 0
    failures = []
    for cls in (classes if classes is not None else _classes):
        ok, failed = _run_class(cls)
        total += ok + len(failed)
        failures.extend(failed)
    sys.stdout.write("\n")
    for name, e in failures:
        sys.stdout.write("FAIL: " + name + "\n  " + str(e) + "\n")
    sys.stdout.write("Ran " + str(total) + " tests\n")
    if len(failures) > 0:
        sys.stdout.write("FAILED (failures=" + str(len(failures)) + ")\n")
        sys.exit(1)
    sys.stdout.write("OK\n")
)NSLIB"
        },
        {"urllib_parse",
         R"NSLIB(_safe = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-~"

def quote(s, safe="/"):
    s = str(s)
    out = ""
    for i in range(_bytelen(s)):
        b = byte_di(s, i)
        ch = chr(b) if b < 128 else ""
        if b < 128 and (ch in _safe or ch in safe):
            out += ch
        else:
            out += "%" + hex(b)[2:].upper().zfill(2)
    return out

def quote_plus(s, safe=""):
    return quote(s, safe).replace("%20", "+")

def unquote(s):
    raw = []
    i = 0
    n = len(s)
    while i < n:
        c = s[i]
        if c == "%" and i + 2 < n + 1:
            try:
                raw.append(int(s[i + 1:i + 3], 16))
                i += 3
                continue
            except Exception:
                pass
        for j in range(_bytelen(c)):
            raw.append(byte_di(c, j))
        i += 1
    out = ""
    k = 0
    while k < len(raw):
        b = raw[k]
        if b < 0x80:
            out += chr(b)
            k += 1
        elif b >= 0xF0 and k + 3 < len(raw) + 0:
            out += chr(((b & 7) << 18) | ((raw[k + 1] & 63) << 12) | ((raw[k + 2] & 63) << 6) | (raw[k + 3] & 63))
            k += 4
        elif b >= 0xE0 and k + 2 < len(raw) + 0:
            out += chr(((b & 15) << 12) | ((raw[k + 1] & 63) << 6) | (raw[k + 2] & 63))
            k += 3
        elif b >= 0xC0 and k + 1 < len(raw) + 0:
            out += chr(((b & 31) << 6) | (raw[k + 1] & 63))
            k += 2
        else:
            out += chr(b)
            k += 1
    return out

def unquote_plus(s):
    return unquote(s.replace("+", " "))

def urlencode(query, doseq=False):
    items = query.items() if isinstance(query, dict) else query
    parts = []
    for k, v in items:
        if doseq and isinstance(v, (list, tuple)):
            for x in v:
                parts.append(quote_plus(k) + "=" + quote_plus(x))
        else:
            parts.append(quote_plus(k) + "=" + quote_plus(v))
    return "&".join(parts)

def parse_qs(qs, keep_blank_values=False):
    out = {}
    if qs == "":
        return out
    for pair in qs.split("&"):
        if pair == "":
            continue
        k, _, v = pair.partition("=")
        k = unquote_plus(k)
        v = unquote_plus(v)
        if v == "" and not keep_blank_values:
            continue
        if k not in out:
            out[k] = []
        out[k].append(v)
    return out

def parse_qsl(qs, keep_blank_values=False):
    out = []
    d = parse_qs(qs, keep_blank_values)
    for k in d:
        for v in d[k]:
            out.append((k, v))
    return out

class ParseResult:
    def __init__(self, scheme, netloc, path, params, query, fragment):
        self.scheme = scheme
        self.netloc = netloc
        self.path = path
        self.params = params
        self.query = query
        self.fragment = fragment
    @property
    def hostname(self):
        h = self.netloc.split("@")[-1]
        return h.split(":")[0] if h != "" else None
    @property
    def port(self):
        h = self.netloc.split("@")[-1]
        if ":" in h:
            return int(h.split(":")[1])
        return None
    @property
    def username(self):
        return self.netloc.split("@")[0].split(":")[0] if "@" in self.netloc else None
    @property
    def password(self):
        return self.netloc.split("@")[0].split(":")[1] if "@" in self.netloc and ":" in self.netloc.split("@")[0] else None
    def geturl(self):
        return urlunparse(self)
    def __str__(self):
        return self.geturl()

def urlparse(url, scheme=""):
    rest = url
    fragment = ""
    query = ""
    netloc = ""
    if "#" in rest:
        rest, _, fragment = rest.partition("#")
    if "?" in rest:
        rest, _, query = rest.partition("?")
    sch = scheme
    i = rest.find(":")
    if i > 0 and rest[:i].replace("+", "").replace("-", "").replace(".", "").isalnum():
        sch = rest[:i].lower()
        rest = rest[i + 1:]
    if rest.startswith("//"):
        rest = rest[2:]
        j = rest.find("/")
        if j < 0:
            netloc = rest
            rest = ""
        else:
            netloc = rest[:j]
            rest = rest[j:]
    return ParseResult(sch, netloc, rest, "", query, fragment)

urlsplit = urlparse

def urlunparse(p):
    url = p.path
    if p.netloc != "" or (p.scheme != "" and p.path.startswith("//")):
        url = "//" + p.netloc + url
    if p.scheme != "":
        url = p.scheme + ":" + url
    if p.query != "":
        url = url + "?" + p.query
    if p.fragment != "":
        url = url + "#" + p.fragment
    return url

urlunsplit = urlunparse

def urljoin(base, url):
    if url == "":
        return base
    if "://" in url:
        return url
    b = urlparse(base)
    if url.startswith("//"):
        return b.scheme + ":" + url
    if url.startswith("/"):
        path = url
    else:
        dir = b.path[:b.path.rfind("/") + 1] if "/" in b.path else "/"
        path = dir + url
    segs = []
    for s in path.split("/"):
        if s == "..":
            if len(segs) > 1:
                segs.pop()
        elif s != ".":
            segs.append(s)
    return b.scheme + "://" + b.netloc + "/".join(segs)
)NSLIB"
        },
        {"uuid",
         R"NSLIB(import random

class UUID:
    def __init__(self, hex):
        self.hex = hex.replace("-", "")
    def __str__(self):
        h = self.hex
        return h[0:8] + "-" + h[8:12] + "-" + h[12:16] + "-" + h[16:20] + "-" + h[20:32]
    def __repr__(self):
        return "UUID('" + str(self) + "')"
    def __eq__(self, o):
        return isinstance(o, UUID) and self.hex == o.hex
    @property
    def int(self):
        n = 0
        for c in self.hex:
            n = n * 16 + "0123456789abcdef".index(c)
        return n

def uuid4():
    digits = "0123456789abcdef"
    h = ""
    for i in range(32):
        h += digits[random.randint(0, 15)]
    h = h[0:12] + "4" + h[13:16] + digits[8 + random.randint(0, 3)] + h[17:32]
    return UUID(h)

def UUID_from(text):
    return UUID(text)
)NSLIB"
        },
    };
    auto it = mods.find(name);
    return it == mods.end() ? nullptr : it->second;
}

}  // namespace pystd
